# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0002_auto_20170607_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PratMus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Faire une liste des pratiques musicales dont il est question',
            },
        ),
        migrations.RenameModel(
            old_name='ElemMus',
            new_name='ExpMus',
        ),
        migrations.AlterModelOptions(
            name='expmus',
            options={'verbose_name': 'Faire une liste des exp\xe9riences musicales dont il est question'},
        ),
        migrations.RenameField(
            model_name='outil',
            old_name='elements_musicaux',
            new_name='experiences_musicales',
        ),
        migrations.AddField(
            model_name='outil',
            name='pratique_musicale',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('Techniques instrumentales (mode de production du son)', 'Techniques instrumentales (mode de production du son)'), ("Activit\xe9 du musicien, du compositeur, de l'interpr\xe8te, du luthier etc.", "Activit\xe9 du musicien, du compositeur, de l'interpr\xe8te, du luthier etc."), ('Pratique professionnelle', 'Pratique professionnelle'), ('Pratique amateur', 'Pratique amateur'), ('Autre', 'Autre')], max_length=200, verbose_name='Pratique musicale'),
        ),
        migrations.AddField(
            model_name='outil',
            name='liste_pratiques',
            field=models.ManyToManyField(to='bdmultimedia.PratMus'),
        ),
    ]
