# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0005_auto_20170608_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElemSocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Faire une liste des \xe9l\xe9ments socio-culturels dont il est question',
            },
        ),
        migrations.AddField(
            model_name='outil',
            name='solicitation_autre',
            field=models.CharField(blank=True, choices=[('Lire', 'Lire'), ('Regarder', 'Regarder'), ('Bricoler', 'Bricoler'), ('Jouer (au sens ludique)', 'Jouer (au sens ludique)'), ('\xc9crire', '\xc9crire'), ('Autre', 'Autre')], max_length=200, verbose_name="En g\xe9n\xe9ral (hors musique) comment sollicite-t-on l'usager?"),
        ),
        migrations.AddField(
            model_name='outil',
            name='solicitation_musicale',
            field=models.CharField(blank=True, choices=[('Interpr\xe9ter', 'Interpr\xe9ter'), ('Reproduire', 'Reproduire'), ('\xc9couter', '\xc9couter'), ('Inventer/composer/improviser', 'Inventer/composer/improviser'), ('Lire', 'Lire'), ('Regarder', 'Regarder'), ('Autre', 'Autre')], max_length=200, verbose_name="Comment sollicite-t-on musicalement l'usager?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='liste_experiences',
            field=models.ManyToManyField(to='bdmultimedia.ExpMus', verbose_name='Faire une liste des exp\xe9riences musicales dont il est question'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='liste_pratiques',
            field=models.ManyToManyField(to='bdmultimedia.PratMus', verbose_name='Faire une liste des pratiques musicales dont il est question'),
        ),
        migrations.AddField(
            model_name='outil',
            name='liste_elements_socio',
            field=models.ManyToManyField(to='bdmultimedia.ElemSocio', verbose_name='Faire une liste des \xe9l\xe9ments socio-culturels dont il est question'),
        ),
    ]
