# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0006_auto_20170608_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionsInter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Donner des exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires',
            },
        ),
        migrations.AddField(
            model_name='outil',
            name='evocaion_litteraire',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('Texte oral', 'Texte oral'), ('Texte \xe9crit', 'Texte \xe9crit'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation litt\xe9raire'),
        ),
        migrations.AddField(
            model_name='outil',
            name='evocaion_plastique',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('Sculpture', 'Sculpture'), ('Installation', 'Instalation'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation plastique'),
        ),
        migrations.AddField(
            model_name='outil',
            name='evocation_autre',
            field=models.CharField(blank=True, choices=[('Aucune', 'Aucune'), ('Litt\xe9rature', 'Litt\xe9rature'), ('Danse', 'Danse'), ('Art plastiques', 'Art plastiques'), ('Th\xe9\xe2tre', 'Th\xe9\xe2tre'), ('Cin\xe9ma', 'Cin\xe9ma'), ('Arts num\xe9riques', 'Arts num\xe9riques'), ('Sports', 'Sports'), ('Neurosciences', 'Neurosciences'), ('Sciences physiques', 'Sciences physiques'), ('Architechture', 'Architechture'), ('Gastronomie', 'Gastronomie'), ('Cirque', 'Cirque'), ('Performance', 'Performance'), ('Anatomie', 'Anatomie'), ('Autre', 'Autre')], max_length=200, verbose_name='Autres disciplines \xe9voqu\xe9es'),
        ),
        migrations.AddField(
            model_name='outil',
            name='evocation_graphique',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('Repr\xe9sentation graphique traditionnelle (partition + notes)', 'Repr\xe9sentation graphique traditionnelle (partition + notes)'), ("Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends", "Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends"), ('Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)', 'Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)'), ('Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)', 'Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)'), ('Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es, cf. ratatouille!!)', 'Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es, cf. ratatouille!!)'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation graphique'),
        ),
        migrations.AddField(
            model_name='outil',
            name='notion_concepts',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=200, verbose_name='Concepts (luminosit\xe9, transparence)'),
        ),
        migrations.AddField(
            model_name='outil',
            name='notion_experiences',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=200, verbose_name='Exp\xe9rience (\xe9motions)'),
        ),
        migrations.AddField(
            model_name='outil',
            name='notion_pratique',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=200, verbose_name='Pratique (processus de cr\xe9ation)'),
        ),
        migrations.AddField(
            model_name='outil',
            name='notions_interdisciplinaires',
            field=models.CharField(blank=True, choices=[('Non', 'Non'), ('Vie du compositeur, interpr\xe8te, d\xe9dica\xe7aire, m\xe9c\xe8ne', 'Vie du compositeur, interpr\xe8te, d\xe9dica\xe7aire, m\xe9c\xe8ne'), ('Organologie', 'Organologie'), ('Lutherie', 'Lutherie'), ('\xc9volution de la profession', '\xc9volution de la profession'), ('Conventions', 'Conventions'), ('Epoques dat\xe9es (ex. les dates du Romantisme ou r\xe9f\xe9rence au 18\xe8)', 'Epoques dat\xe9es (ex. les dates du Romantisme ou r\xe9f\xe9rence au 18\xe8)'), ('Oeuvres (\xe0 titre documentaires)', 'Oeuvres (\xe0 titre documentaires)'), ('Contexte de production', 'Contexte de production'), ('Contexte de r\xe9ception', 'Contexte de r\xe9ception'), ('Contexte de cr\xe9ation (au sens de "la premi\xe8re")', 'Contexte de cr\xe9ation (au sens de "la premi\xe8re")'), ('Autre', 'Autre')], max_length=200, verbose_name='Donner des exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'),
        ),
        migrations.AddField(
            model_name='outil',
            name='sonore_valeur',
            field=models.CharField(blank=True, choices=[('Premier plan', 'Premier Plan'), ('Arri\xe8re plan', 'Arri\xe8re plan'), ('Alternance', 'Alternance'), ('Aucune', 'Aucune'), ('Autre', 'Autre')], max_length=200, verbose_name='Mise en valeur du sonore'),
        ),
        migrations.AddField(
            model_name='outil',
            name='temps_musique',
            field=models.TimeField(null=True, verbose_name='Temps de musique seule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outil',
            name='temps_musique_paroles',
            field=models.TimeField(null=True, verbose_name='Temps de parole et musique superpos\xe9es'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outil',
            name='temps_parole',
            field=models.TimeField(null=True, verbose_name='Temps de parole seule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outil',
            name='exemples_notions_interdisciplinaires',
            field=models.ManyToManyField(to='bdmultimedia.NotionsInter'),
        ),
    ]
