# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0007_auto_20170611_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='temps_musique',
            field=models.TimeField(blank=True, verbose_name='Temps de musique seule'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_musique_paroles',
            field=models.TimeField(blank=True, verbose_name='Temps de parole et musique superpos\xe9es'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_parole',
            field=models.TimeField(blank=True, verbose_name='Temps de parole seule'),
        ),
    ]
