# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0008_auto_20170611_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='notions_interdisciplinaires',
        ),
    ]
