# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0009_remove_outil_notions_interdisciplinaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='temps_musique',
            field=models.CharField(blank=True, max_length=50, verbose_name='Temps de musique seule(hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_musique_paroles',
            field=models.CharField(blank=True, max_length=50, verbose_name='Temps de parole et musique superpos\xe9es(hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_parole',
            field=models.CharField(blank=True, max_length=50, verbose_name='Temps de parole seule(hh:mm:ss)'),
        ),
    ]
