# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0010_auto_20170612_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='exemples_notions_interdisciplinaires',
            field=models.ManyToManyField(to='bdmultimedia.NotionsInter', verbose_name='Donner des exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'),
        ),
    ]
