# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0011_auto_20170612_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outil',
            old_name='temps_musique',
            new_name='temps_mus',
        ),
        migrations.RenameField(
            model_name='outil',
            old_name='temps_musique_paroles',
            new_name='temps_mus_par',
        ),
        migrations.RenameField(
            model_name='outil',
            old_name='temps_parole',
            new_name='temps_par',
        ),
    ]
