# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0013_auto_20170613_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='temps_mus',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='temps_mus_par',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='temps_par',
        ),
    ]
