# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0014_auto_20170613_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='temps_mus',
            field=models.CharField(blank=True, default='00:00:00', max_length=50, verbose_name='Temps de musique seule(hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='outil',
            name='temps_mus_par',
            field=models.CharField(blank=True, default='00:00:00', max_length=50, verbose_name='Temps de parole et musique superpos\xe9es(hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='outil',
            name='temps_par',
            field=models.CharField(blank=True, default='00:00:00', max_length=50, verbose_name='Temps de parole seule(hh:mm:ss)'),
        ),
    ]
