# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0016_auto_20170613_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='nb_animaux_indetermines',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'animaux au genre ind\xe9termin\xe9"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_animaux_total',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'animaux total"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_femelles',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de femelles'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_femmes',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de femmes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_hommes',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'hommes"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_humains_indetermines',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'humains au genre ind\xe9termin\xe9"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_humains_total',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'humains total"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_instr_anime_femmes',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'instruments anim\xe9s f\xe9minins"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_instr_anime_hommes',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'instruments anim\xe9s masculins"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_instr_anime_indetermines',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'instruments anim\xe9s au genre ind\xe9termin\xe9"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_instr_anime_total',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'instruments anim\xe9s total"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_males',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de m\xe2les'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_obj_anime_femmes',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'objets anim\xe9s feminins"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_obj_anime_hommes',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'objets anim\xe9s masculins"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_obj_anime_indetermines',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'objets anim\xe9s au genre ind\xe9termin\xe9"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_obj_anime_total',
            field=models.PositiveIntegerField(null=True, verbose_name="Nombre d'objets anim\xe9s total"),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_anime_femmes',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnages anim\xe9s femmes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_anime_hommes',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnages anim\xe9s hommes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_anime_indetermines',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnages anim\xe9s au genre ind\xe9termin\xe9'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_anime_total',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnages anim\xe9s total'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_fictifs_femmes',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnage fictifs f\xe9minins \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_fictifs_hommes',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnage fictifs masculins \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_fictifs_indetermines',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnage fictifs au genre ind\xe9termin\xe9 \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AddField(
            model_name='outil',
            name='nb_pers_fictifs_total',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre de personnage fictifs total \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_animaux_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des animaux femelles'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_animaux_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des animaux m\xe2les'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_animaux_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des animaux neutres'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_humain_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des femmes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_humain_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des hommes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_humain_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des neutres'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_instr_anime_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des instruments anthropomorphes f\xe9minins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_instr_anime_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des instruments anthropomorphes masculins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_instr_anime_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des instruments anthropomorphes neutres'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_obj_anime_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des objets anthropomorphes f\xe9minins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_obj_anime_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des objets anthropomorphes masculins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_obj_anime_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des objets anthropomorphes neutres'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_anime_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages anim\xe9s femmes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_anime_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages anim\xe9s hommes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_anime_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages anim\xe9s neutres'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_fictif_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages fictifs f\xe9minins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_fictif_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages fictifs masculins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_fictif_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages fictifs neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='duree',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, verbose_name='Dur\xe9e (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, verbose_name='Temps de musique seule (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus_par',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, verbose_name='Temps de parole et musique superpos\xe9es (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_par',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, verbose_name='Temps de parole seule (hh:mm:ss)'),
        ),
    ]
