# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0017_auto_20170613_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='duree',
            field=models.DurationField(verbose_name='Dur\xe9e (hh:mm:ss)'),
        ),
    ]
