# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0021_auto_20170613_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='autre_elements_socio',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_evocation_autre',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_evocation_graphique',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_evocation_litteraire',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_evocation_plastique',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_experiences_musicales',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_format',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_forme_narrative',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_materiau_musical',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_mode_hebergement',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_narration_langue',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_pratique_musicale',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_producteur',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_solicitation_autre',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_solicitation_musicale',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_sonore_valeur',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_sous_titre',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='autre_support',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
    ]
