# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0022_auto_20170613_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='evocaion_plastique',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Sculpture', 'Sculpture'), ('Installation', 'Installation'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation plastique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_graphique',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Repr\xe9sentation graphique traditionnelle (partition + notes)', 'Repr\xe9sentation graphique traditionnelle (partition + notes)'), ("Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)", "Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)"), ('Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)', 'Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)'), ('Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)', 'Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)'), ('Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es, cf. ratatouille!!)', 'Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es, cf. ratatouille!!)'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation graphique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='narration_langue',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fran\xe7ais', 'Fran\xe7ais'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Allemand', 'Allemand'), ('Italien', 'Italien'), ('Portugais', 'Portugais'), ('Autre', 'Autre')], max_length=200, verbose_name='Langue de la narration'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='titre',
            field=models.CharField(max_length=200, verbose_name="Titre de l'outil"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='url',
            field=models.URLField(unique=True, verbose_name="Chemin d'acc\xe8s direct (c\xe0d quand on a fini de parcourir le site)"),
        ),
    ]
