# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:04
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0023_auto_20170615_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='elements_socio',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Vie du compositeur, interpr\xe8te, d\xe9dica\xe7aire, m\xe9c\xe8ne', 'Vie du compositeur, interpr\xe8te, d\xe9dica\xe7aire, m\xe9c\xe8ne'), ('Organologie', 'Organologie'), ('Lutherie', 'Lutherie'), ('\xc9volution de la profession', '\xc9volution de la profession'), ('Conventions', 'Conventions'), ('Epoques dat\xe9es (ex. les dates du Romantisme ou r\xe9f\xe9rence au 18\xe8)', 'Epoques dat\xe9es (ex. les dates du Romantisme ou r\xe9f\xe9rence au 18\xe8)'), ('Oeuvres (\xe0 titre documentaires)', 'Oeuvres (\xe0 titre documentaires)'), ('Contexte de production', 'Contexte de production'), ('Contexte de r\xe9ception', 'Contexte de r\xe9ception'), ('Contexte de cr\xe9ation (au sens de "la premi\xe8re")', 'Contexte de cr\xe9ation (au sens de "la premi\xe8re")'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - el\xe9ments socioculturels et historiques'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='experiences_musicales',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ("Techniques d'\xe9coute", "Techniques d'\xe9coute"), ('Exp\xe9rience v\xe9cue', 'Exp\xe9rience v\xe9cue'), ('Le concert', 'Le concert'), ('Les r\xe9p\xe9titions (g\xe9n\xe9rale, raccord, etc.)', 'Les r\xe9p\xe9titions (g\xe9n\xe9rale, raccord, etc.)'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - experiences musicales'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='materiau_musical',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Son', 'Son'), ('Structure', 'Structure'), ('Language musical', 'Language musical'), ('Genre (op\xe9ra, symphonique)', 'Genre (op\xe9ra, symphonique)'), ('Style (Classique, Romantique, Contemporain)', 'Style (Classique, Romantique, Contemporain)'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - mat\xe9riau musical'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='pratique_musicale',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Techniques instrumentales (mode de production du son)', 'Techniques instrumentales (mode de production du son)'), ("Activit\xe9 du musicien, du compositeur, de l'interpr\xe8te, du luthier etc.", "Activit\xe9 du musicien, du compositeur, de l'interpr\xe8te, du luthier etc."), ('Pratique professionnelle', 'Pratique professionnelle'), ('Pratique amateur', 'Pratique amateur'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - pratique musicale'),
        ),
    ]
