# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0024_auto_20170617_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='date_verif',
            field=models.DateField(null=True, verbose_name='Date de la derni\xe8re v\xe9rification du lien'),
        ),
        migrations.AddField(
            model_name='outil',
            name='lien_actif',
            field=models.BooleanField(default=True, verbose_name='Lien actif'),
        ),
    ]
