# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0027_auto_20170617_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='autre_onglet',
            field=models.CharField(max_length=200, null=True, verbose_name='Si autre onglet inscrire ici en format onglet n\xb0x = xxxxx'),
        ),
        migrations.AddField(
            model_name='outil',
            name='deuxieme_onglet',
            field=models.CharField(choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Deuxi\xe8me onglet \xe0 ouvrir'),
        ),
        migrations.AddField(
            model_name='outil',
            name='premier_onglet',
            field=models.CharField(choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Premier onglet \xe0 ouvrir'),
        ),
        migrations.AddField(
            model_name='outil',
            name='quatrieme_onglet',
            field=models.CharField(choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Quatri\xe8me onglet \xe0 ouvrir'),
        ),
        migrations.AddField(
            model_name='outil',
            name='troisieme_onglet',
            field=models.CharField(choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Troisi\xe8me onglet \xe0 ouvrir'),
        ),
    ]
