# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0028_auto_20170617_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='autre_mode_consultation',
            field=models.CharField(max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AddField(
            model_name='outil',
            name='mode_consultation',
            field=models.CharField(choices=[("Consultation r\xe9serv\xe9e aux membres de l'organisme producteur", "Consultation r\xe9serv\xe9e aux membres de l'organisme producteur"), ("Consultation payante \xe0 l'abonnement", "Consultation payante \xe0 l'abonnement"), ('Consultation payante \xe0 la pi\xe8ce', 'Consultation payante \xe0 la pi\xe8ce'), ('Consultation libre \xe0 tous', 'Consultation libre \xe0 tous'), ('T\xe9l\xe9chargement payant', 'T\xe9l\xe9chargement payant'), ('T\xe9l\xe9chargement gratuit', 'T\xe9l\xe9chargement gratuit'), ('T\xe9l\xe9chargement gratuit et mises \xe0 jour payantes', 'T\xe9l\xe9chargement gratuit et mises \xe0 jour payantes'), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Mode de consultation offert au public'),
        ),
    ]
