# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:49
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0029_auto_20170617_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='sous_titre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pas de sous titrage', 'Pas de sous titrage'), ('Fran\xe7ais', 'Fran\xe7ais'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Allemand', 'Allemand'), ('Italien', 'Italien'), ('Portugais', 'Portugais'), ('Autre', 'Autre')], max_length=200, verbose_name='Sous-titrage'),
        ),
    ]
