# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0031_auto_20170620_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='notion_concepts',
            field=models.ManyToManyField(to='bdmultimedia.NotConcept', verbose_name='Concepts (luminosit\xe9, transparence)'),
        ),
    ]
