# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0033_outil_notion_pratiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='notion_experiences',
            field=models.ManyToManyField(to='bdmultimedia.NotExp', verbose_name='Exp\xe9rience (\xe9motions)'),
        ),
    ]
