# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0034_outil_notion_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='notion_concepts',
            field=models.ManyToManyField(to='bdmultimedia.NotConcept', verbose_name='\xc0 partir de quelle notion? - Concepts (luminosit\xe9, transparence)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_experiences',
            field=models.ManyToManyField(to='bdmultimedia.NotExp', verbose_name='\xc0 partir de quelle notion? - Exp\xe9rience (\xe9motions)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_pratiques',
            field=models.ManyToManyField(to='bdmultimedia.NotPratique', verbose_name='\xc0 partir de quelle notion? - Pratique (processus de cr\xe9ation)'),
        ),
    ]
