# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bdmultimedia', '0035_auto_20170629_1253'),
    ]

    operations = [

        migrations.AlterField(
            model_name='outil',
            name='audiodescription',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non'), ("Ne s'applique pas", "Ne s'applique pas")], max_length=200, verbose_name='Audiodescription (mal voyants)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_elements_socio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_evocation_autre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_evocation_graphique',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_evocation_litteraire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_evocation_plastique',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_experiences_musicales',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_format',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_forme_narrative',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_materiau_musical',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_mode_consultation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_mode_hebergement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_narration_langue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_onglet',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Si autre onglet inscrire ici en format onglet n\xb0x = xxxxx'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_pratique_musicale',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_producteur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_solicitation_autre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_solicitation_musicale',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_sonore_valeur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_sous_titre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='autre_support',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre, pr\xe9cisez:'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='commentaire_nombre',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de commentaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='date_verif',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la derni\xe8re v\xe9rification du lien (aaaa/mm/jj)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='depouillement_date',
            field=models.DateField(blank=True, verbose_name='Date du d\xe9pouillement (aaaa/mm/jj)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='deuxieme_onglet',
            field=models.CharField(blank=True, choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Deuxi\xe8me onglet \xe0 ouvrir'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='elements_socio',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ('Vie du compositeur, interpr\xe8te, d\xe9dica\xe7aire, m\xe9c\xe8ne', 'Vie du compositeur, interpr\xe8te, d\xe9dica\xe7aire, m\xe9c\xe8ne'), ('Organologie', 'Organologie'), ('Lutherie', 'Lutherie'), ('\xc9volution de la profession', '\xc9volution de la profession'), ('Conventions', 'Conventions'), ('Epoques dat\xe9es (ex. les dates du Romantisme ou r\xe9f\xe9rence au 18\xe8)', 'Epoques dat\xe9es (ex. les dates du Romantisme ou r\xe9f\xe9rence au 18\xe8)'), ('Oeuvres (\xe0 titre documentaires)', 'Oeuvres (\xe0 titre documentaires)'), ('Contexte de production', 'Contexte de production'), ('Contexte de r\xe9ception', 'Contexte de r\xe9ception'), ('Contexte de cr\xe9ation (au sens de "la premi\xe8re")', 'Contexte de cr\xe9ation (au sens de "la premi\xe8re")'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - el\xe9ments socioculturels et historiques'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocaion_litteraire',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ('Texte oral', 'Texte oral'), ('Texte \xe9crit', 'Texte \xe9crit'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation litt\xe9raire'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocaion_plastique',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ('Sculpture', 'Sculpture'), ('Installation', 'Installation'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation plastique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_autre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Aucune', 'Aucune'), ('Litt\xe9rature', 'Litt\xe9rature'), ('Danse', 'Danse'), ('Art plastiques', 'Art plastiques'), ('Th\xe9\xe2tre', 'Th\xe9\xe2tre'), ('Cin\xe9ma', 'Cin\xe9ma'), ('Arts num\xe9riques', 'Arts num\xe9riques'), ('Sports', 'Sports'), ('Neurosciences', 'Neurosciences'), ('Sciences physiques', 'Sciences physiques'), ('Architechture', 'Architechture'), ('Gastronomie', 'Gastronomie'), ('Cirque', 'Cirque'), ('Performance', 'Performance'), ('Anatomie', 'Anatomie'), ('Autre', 'Autre')], max_length=200, verbose_name='Autres disciplines \xe9voqu\xe9es'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_graphique',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ('Repr\xe9sentation graphique traditionnelle (partition + notes)', 'Repr\xe9sentation graphique traditionnelle (partition + notes)'), ("Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)", "Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)"), ('Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)', 'Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)'), ('Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)', 'Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)'), ('Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es, cf. ratatouille!!)', 'Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es, cf. ratatouille!!)'), ('Autre', 'Autre')], max_length=200, verbose_name='\xc9vocation graphique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='exemples_notions_interdisciplinaires',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.NotionsInter', verbose_name='Donner des exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='experiences_musicales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ("Techniques d'\xe9coute", "Techniques d'\xe9coute"), ('Exp\xe9rience v\xe9cue', 'Exp\xe9rience v\xe9cue'), ('Le concert', 'Le concert'), ('Les r\xe9p\xe9titions (g\xe9n\xe9rale, raccord, etc.)', 'Les r\xe9p\xe9titions (g\xe9n\xe9rale, raccord, etc.)'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - experiences musicales'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='format',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ecrit (texte, dessin)', 'Ecrit (texte, dessin)'), ('Audio', 'Audio'), ('Audiovisuel', 'Audiovisuel'), ('Immersif', 'Immersif'), ('R\xe9alit\xe9 augment\xe9e', 'R\xe9alit\xe9 augment\xe9e'), ('Autre', 'Autre')], max_length=200, verbose_name="Format de l'outil"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='forme_narrative',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entrevue', 'Entrevue'), ('Fiction', 'Fiction'), ("Synopsis (r\xe9cit fid\xe8le au programme de l'oeuvre)", "Synopsis (r\xe9cit fid\xe8le au programme de l'oeuvre)"), ('Web-s\xe9rie (plusieurs occurences qui ont un lien entre elles)', 'Web-s\xe9rie (plusieurs occurences qui ont un lien entre elles)'), ('Animation', 'Animation'), ('Art et essai', 'Art et essai'), ('Vulgarisation', 'Vulgarisation'), ('Creative commons (sur le mod\xe8le wiki)', 'Creative commons (sur le mod\xe8le wiki)'), ('Reportage', 'Reportage'), ('Jeu', 'Jeu'), ('Autre', 'Autre')], max_length=200, verbose_name='Forme narrative g\xe9n\xe9rale'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='interface_type',
            field=models.CharField(blank=True, choices=[('Collaborative', 'Collaborative'), ('Interactive', 'Interactive'), ('Neutre', 'Neutre')], max_length=200, null=True, verbose_name="Type d'interface"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='language_des_signes',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non'), ("Ne s'applique pas", "Ne s'applique pas")], max_length=200, verbose_name='Language des signes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='liste_elements_socio',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.ElemSocio', verbose_name='Faire une liste des \xe9l\xe9ments socio-culturels dont il est question'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='liste_experiences',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.ExpMus', verbose_name='Faire une liste des exp\xe9riences musicales dont il est question'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='liste_materiau',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.ElemMus', verbose_name='Faire une liste des \xe9l\xe9ments musicaux dont il est question'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='liste_pratiques',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.PratMus', verbose_name='Faire une liste des pratiques musicales dont il est question'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='malentendants',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non'), ("Ne s'applique pas", "Ne s'applique pas")], max_length=200, verbose_name='Sous titrage malentendants'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='materiau_musical',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ('Son', 'Son'), ('Structure', 'Structure'), ('Language musical', 'Language musical'), ('Genre (op\xe9ra, symphonique)', 'Genre (op\xe9ra, symphonique)'), ('Style (Classique, Romantique, Contemporain)', 'Style (Classique, Romantique, Contemporain)'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - mat\xe9riau musical'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mise_en_ligne_date',
            field=models.DateField(blank=True, verbose_name='Date de la mise en ligne (aaaa/mm/jj)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mode_consultation',
            field=models.CharField(blank=True, choices=[("Consultation r\xe9serv\xe9e aux membres de l'organisme producteur", "Consultation r\xe9serv\xe9e aux membres de l'organisme producteur"), ("Consultation payante \xe0 l'abonnement", "Consultation payante \xe0 l'abonnement"), ('Consultation payante \xe0 la pi\xe8ce', 'Consultation payante \xe0 la pi\xe8ce'), ('Consultation libre \xe0 tous', 'Consultation libre \xe0 tous'), ('T\xe9l\xe9chargement payant', 'T\xe9l\xe9chargement payant'), ('T\xe9l\xe9chargement gratuit', 'T\xe9l\xe9chargement gratuit'), ('T\xe9l\xe9chargement gratuit et mises \xe0 jour payantes', 'T\xe9l\xe9chargement gratuit et mises \xe0 jour payantes'), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Mode de consultation offert au public'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mode_hebergement',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Youtube / Vimeo, etc..', 'Youtube / Vimeo, etc..'), ('Portail institutionnel', 'Portail institutionnel'), ('R\xe9seau social', 'R\xe9seau social'), ('Cloud', 'Cloud'), ('Autre', 'Autre')], max_length=200, verbose_name="Mode d'h\xe9bergement sur la toile"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='narration_langue',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fran\xe7ais', 'Fran\xe7ais'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Allemand', 'Allemand'), ('Italien', 'Italien'), ('Portugais', 'Portugais'), ('Autre', 'Autre')], max_length=200, verbose_name='Langue de la narration'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_animaux_indetermines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'animaux au genre ind\xe9termin\xe9"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_animaux_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'animaux total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_femelles',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de femelles'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_femmes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Nombre de femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_hommes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="Nombre d'hommes"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_humains_indetermines',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="Nombre d'humains au genre ind\xe9termin\xe9"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_humains_total',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="Nombre d'humains total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_femmes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'instruments anim\xe9s f\xe9minins"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_hommes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'instruments anim\xe9s masculins"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_indetermines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'instruments anim\xe9s au genre ind\xe9termin\xe9"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'instruments anim\xe9s total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_males',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de m\xe2les'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_obj_anime_femmes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'objets anim\xe9s feminins"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_obj_anime_hommes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'objets anim\xe9s masculins"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_obj_anime_indetermines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'objets anim\xe9s au genre ind\xe9termin\xe9"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_obj_anime_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'objets anim\xe9s total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_femmes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnages anim\xe9s femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_hommes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnages anim\xe9s hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_indetermines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnages anim\xe9s au genre ind\xe9termin\xe9'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnages anim\xe9s total'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_fictifs_femmes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnage fictifs f\xe9minins \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_fictifs_hommes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnage fictifs masculins \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_fictifs_indetermines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnage fictifs au genre ind\xe9termin\xe9 \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_fictifs_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de personnage fictifs total \xe9voqu\xe9s dans la narration'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_concepts',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.NotConcept', verbose_name='\xc0 partir de quelle notion? - Concepts (luminosit\xe9, transparence)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_experiences',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.NotExp', verbose_name='\xc0 partir de quelle notion? - Exp\xe9rience (\xe9motions)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_pratiques',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.NotPratique', verbose_name='\xc0 partir de quelle notion? - Pratique (processus de cr\xe9ation)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='pratique_musicale',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ('Techniques instrumentales (mode de production du son)', 'Techniques instrumentales (mode de production du son)'), ("Activit\xe9 du musicien, du compositeur, de l'interpr\xe8te, du luthier etc.", "Activit\xe9 du musicien, du compositeur, de l'interpr\xe8te, du luthier etc."), ('Pratique professionnelle', 'Pratique professionnelle'), ('Pratique amateur', 'Pratique amateur'), ('Autre', 'Autre')], max_length=200, verbose_name='Contenu musical - pratique musicale'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='premier_onglet',
            field=models.CharField(blank=True, choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Premier onglet \xe0 ouvrir'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pr\xe9ciser le nom complet du producteur'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Particulier', 'Particulier'), ('Organisme de diffusion (OSM, Festival)', 'Organisme de diffusion (OSM, Festival)'), ('Organisme de formation professionnelle (CQM, ARIAM, CFMI)', 'Organisme de formation professionnelle (CQM, ARIAM, CFMI)'), ('Groupe de recherche (P2M, Groupe de recherche sur la m\xe9diation culturelle)', 'Groupe de recherche (P2M, Groupe de recherche sur la m\xe9diation culturelle)'), ('Organismes \xe9ducatif (Ecole de musique, TEDX)', 'Organismes \xe9ducatif (Ecole de musique, TEDX)'), ('Autre', 'Autre')], max_length=200, verbose_name='Producteurs'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='quatrieme_onglet',
            field=models.CharField(blank=True, choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Quatri\xe8me onglet \xe0 ouvrir'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des animaux femelles'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des animaux m\xe2les'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des animaux neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des instruments anthropomorphes f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des instruments anthropomorphes masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des instruments anthropomorphes neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_obj_anime_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des objets anthropomorphes f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_obj_anime_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des objets anthropomorphes masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_obj_anime_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des objets anthropomorphes neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages anim\xe9s femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages anim\xe9s hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages anim\xe9s neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_fictif_femme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages fictifs f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_fictif_homme',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages fictifs masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_fictif_neutre',
            field=models.CharField(blank=True, max_length=200, verbose_name='R\xf4le des personnages fictifs neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.URLField(blank=True, verbose_name="Chemin d'acc\xe8s au site d'h\xe9bergement"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='solicitation_autre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lire', 'Lire'), ('Regarder', 'Regarder'), ('Bricoler', 'Bricoler'), ('Jouer (au sens ludique)', 'Jouer (au sens ludique)'), ('\xc9crire', '\xc9crire'), ('Autre', 'Autre')], max_length=200, verbose_name="En g\xe9n\xe9ral (hors musique) comment sollicite-t-on l'usager?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='solicitation_musicale',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Interpr\xe9ter', 'Interpr\xe9ter'), ('Reproduire', 'Reproduire'), ('\xc9couter', '\xc9couter'), ('Inventer/composer/improviser', 'Inventer/composer/improviser'), ('Lire', 'Lire'), ('Regarder', 'Regarder'), ('Autre', 'Autre')], max_length=200, verbose_name="Comment sollicite-t-on musicalement l'usager?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sonore_valeur',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Premier plan', 'Premier Plan'), ('Arri\xe8re plan', 'Arri\xe8re plan'), ('Alternance', 'Alternance'), ('Aucune', 'Aucune'), ('Autre', 'Autre')], max_length=200, verbose_name='Mise en valeur du sonore'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sous_titre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pas de sous titrage', 'Pas de sous titrage'), ('Fran\xe7ais', 'Fran\xe7ais'), ('Anglais', 'Anglais'), ('Espagnol', 'Espagnol'), ('Allemand', 'Allemand'), ('Italien', 'Italien'), ('Portugais', 'Portugais'), ('Autre', 'Autre')], max_length=200, verbose_name='Sous-titrage'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='support_diffusion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ordinateur', 'Ordinateur'), ('Smartphone', 'Smartphone'), ('Tablette', 'Tablette'), ('Lunettes 3D', 'Lunettes 3D'), ('Consoles de JV', 'Consoles de JV'), ('DVD', 'DVD'), ('CD', 'CD'), ('Autre', 'Autre')], max_length=200, verbose_name='Support de diffusion'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, verbose_name='Temps de musique seule (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus_par',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, verbose_name='Temps de parole et musique superpos\xe9es (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_par',
            field=models.CharField(blank=True, default='00:00:00', max_length=8, verbose_name='Temps de parole seule (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='troisieme_onglet',
            field=models.CharField(blank=True, choices=[("Disponible sur la page d'acc\xe8s", "Disponible sur la page d'acc\xe8s"), ('\xc9ducation', '\xc9ducation'), ('Diffusion', 'Diffusion'), ('M\xe9diation', 'M\xe9diation'), ('Valorisation', 'Valorisation'), ('Exp\xe9rimentation', 'Exp\xe9rimentation'), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('D\xe9couvrir', 'D\xe9couvrir'), ('Programmation', 'Programmation'), ("Ne s'applique pas", "Ne s'applique pas"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Sous quel onglet du site est r\xe9f\xe9renc\xe9 cet outil - Troisi\xe8me onglet \xe0 ouvrir'),
        ),
    ]
