# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0037_auto_20170714_1038'),
    ]

    operations = [

    ]
