# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 14:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0038_auto_20170714_1038'),
    ]

    operations = [

    ]
