# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0040_remove_outil_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='date_verif',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la derni\xe8re v\xe9rification du lien (aaaa-mm-jj)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='depouillement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du d\xe9pouillement (aaaa-mm-jj)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mise_en_ligne_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la mise en ligne (aaaa-mm-jj)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='titre',
            field=models.CharField(help_text="Entrez le titre de l'outil", max_length=200, verbose_name="Titre de l'outil"),
        ),
    ]
