# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0042_auto_20170721_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notexp',
            options={'verbose_name': 'Notion Exp\xe9rience'},
        ),
    ]
