# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0043_auto_20170721_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemmus',
            options={'verbose_name': '\xe9l\xe9ments musicaux'},
        ),
        migrations.AlterModelOptions(
            name='elemsocio',
            options={'verbose_name': '\xe9l\xe9ments socio-culturels'},
        ),
        migrations.AlterModelOptions(
            name='expmus',
            options={'verbose_name': 'exp\xe9riences musicales'},
        ),
        migrations.AlterModelOptions(
            name='notionsinter',
            options={'verbose_name': 'exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'},
        ),
        migrations.AlterModelOptions(
            name='pratmus',
            options={'verbose_name': 'pratiques musicales'},
        ),
    ]
