# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 01:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0044_auto_20170721_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='producteur_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Particulier', 'Particulier'), ('Organisme de diffusion (OSM, Festival)', 'Organisme de diffusion (OSM, Festival)'), ('Organisme de formation professionnelle (CQM, ARIAM, CFMI)', 'Organisme de formation professionnelle (CQM, ARIAM, CFMI)'), ('Groupe de recherche (P2M, Groupe de recherche sur la m\xe9diation culturelle)', 'Groupe de recherche (P2M, Groupe de recherche sur la m\xe9diation culturelle)'), ('Organismes \xe9ducatif (Ecole de musique, TEDX)', 'Organismes \xe9ducatif (Ecole de musique, TEDX)'), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Producteurs'),
        ),
    ]
