# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0045_auto_20170721_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='producteur_type',
        ),
    ]
