# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 19:05
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0050_outil_producteur_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='forme_narrative',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Entrevue', 'Entrevue'), ('Fiction', 'Fiction'), ("Synopsis (r\xe9cit fid\xe8le au programme de l'oeuvre)", "Synopsis (r\xe9cit fid\xe8le au programme de l'oeuvre)"), ('Web-s\xe9rie (plusieurs occurences qui ont un lien entre elles)', 'Web-s\xe9rie (plusieurs occurences qui ont un lien entre elles)'), ('Animation', 'Animation'), ('Art et essai', 'Art et essai'), ('Vulgarisation', 'Vulgarisation'), ('Creative commons (sur le mod\xe8le wiki)', 'Creative commons (sur le mod\xe8le wiki)'), ('Reportage', 'Reportage'), ('Jeu', 'Jeu'), ('Autre', 'Autre')], max_length=221, verbose_name='Forme narrative g\xe9n\xe9rale'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Particulier', 'Particulier'), ('Organisme de diffusion (OSM, Festival)', 'Organisme de diffusion (OSM, Festival)'), ('Organisme de formation professionnelle (CQM, ARIAM, CFMI)', 'Organisme de formation professionnelle (CQM, ARIAM, CFMI)'), ('Groupe de recherche (P2M, Groupe de recherche sur la m\xe9diation culturelle)', 'Groupe de recherche (P2M, Groupe de recherche sur la m\xe9diation culturelle)'), ('Organismes \xe9ducatif (Ecole de musique, TEDX)', 'Organismes \xe9ducatif (Ecole de musique, TEDX)'), ('Autre', 'Autre')], max_length=400, verbose_name='Producteurs'),
        ),
    ]
