# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 19:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0054_auto_20170723_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='evocation_graphique',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Non', 'Non'), ('Repr\xe9sentation graphique traditionnelle (partition + notes)', 'Repr\xe9sentation graphique traditionnelle (partition + notes)'), ("Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)", "Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)"), ('Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)', 'Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)'), ('Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)', 'Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)'), ('Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es; cf. ratatouille!!)', 'Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es; cf. ratatouille!!)'), ('Autre', 'Autre')], max_length=482, verbose_name='\xc9vocation graphique'),
        ),
    ]
