# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0055_auto_20170723_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outil',
            old_name='evocaion_litteraire',
            new_name='evocation_litteraire',
        ),
        migrations.RenameField(
            model_name='outil',
            old_name='evocaion_plastique',
            new_name='evocation_plastique',
        ),
    ]
