# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0056_auto_20170723_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='date_verif',
            field=models.DateField(null=True, verbose_name='Date de la derni\xe8re v\xe9rification du lien'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.URLField(verbose_name="Chemin d'acc\xe8s au site d'h\xe9bergement"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='titre',
            field=models.CharField(max_length=200, verbose_name="Titre de l'outil"),
        ),
    ]
