# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0060_auto_20180205_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'types de producteurs',
            },
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_producteur',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='date_verif',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='lien_actif',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='producteur_types',
        ),
        migrations.AddField(
            model_name='outil',
            name='ensemble_thematique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=4, verbose_name="Cet outil fait-il partie d'un ensemble th\xe9matique du m\xeame type? (regroup\xe9 par l'organisme producteur)"),
        ),
        migrations.AddField(
            model_name='outil',
            name='ensemble_thematique_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Si oui, quel est le nom de cet ensemble?'),
        ),
        migrations.AddField(
            model_name='outil',
            name='producteur_type',
            field=models.ManyToManyField(to='bdmultimedia.ProdType', verbose_name='Qui est le producteurde cet outil?'),
        ),
    ]
