# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0061_auto_20180205_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDiffusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'supports de diffusion',
            },
        ),
        migrations.AlterModelOptions(
            name='prodtype',
            options={'verbose_name': 'types de producteur'},
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_support',
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_nom',
            field=models.CharField(max_length=200, verbose_name='Pr\xe9ciser le nom complet du/des producteur(s)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_type',
            field=models.ManyToManyField(to='bdmultimedia.ProdType', verbose_name='Qui est le producteur de cet outil?'),
        ),
        migrations.RemoveField(
            model_name='outil',
            name='support_diffusion',
        ),
        migrations.AddField(
            model_name='outil',
            name='support_diffusion',
            field=models.ManyToManyField(to='bdmultimedia.SupportDiffusion', verbose_name='Support de diffusion'),
        ),
    ]
