# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0062_auto_20180205_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatOutil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': "format de l'outil",
            },
        ),
        migrations.CreateModel(
            name='FormeNarrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'forme narrative',
            },
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_format',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_forme_narrative',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='format',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='forme_narrative',
        ),
        migrations.AddField(
            model_name='outil',
            name='format',
            field=models.ManyToManyField(to='bdmultimedia.FormatOutil', verbose_name="Format de l'outil"),
        ),
        migrations.AddField(
            model_name='outil',
            name='forme_narrative',
            field=models.ManyToManyField(to='bdmultimedia.FormeNarrative', verbose_name='Forme narrative g\xe9n\xe9rale'),
        ),
    ]
