# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0063_auto_20180205_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='duree',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='Dur\xe9e'),
        ),
    ]
