# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0065_auto_20180208_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='interface_autre',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AddField(
            model_name='outil',
            name='personnification_autre',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AddField(
            model_name='outil',
            name='personnification_service',
            field=models.CharField(choices=[('Service g\xe9n\xe9rique', 'Service g\xe9n\xe9rique'), ('Service sp\xe9cialis\xe9', 'Service sp\xe9cialis\xe9 (public cat\xe9goris\xe9)'), ('Service personnalis\xe9 et/ou individualis\xe9', 'Service personnalis\xe9 et/ou individualis\xe9'), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Degr\xe9s de personnification du service'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='interface',
            field=models.CharField(choices=[('Simple consultation', 'Simple consultation'), ('Participation limit\xe9e', "Participation limit\xe9e (l'usager est actif mais se contente de r\xe9pondre aux consignes)"), ('Participation dynamique', "Participation dynamique (l'usager co-construit le service)"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name="Que permet l'interface?"),
        ),
    ]
