# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0068_auto_20180208_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangueNarration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Langue de la narration',
            },
        ),
        migrations.CreateModel(
            name='SousTitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Langue de la narration',
            },
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_mode_consultation',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_narration_langue',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_sous_titre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='narration_langue',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='sous_titre',
        ),
        migrations.AddField(
            model_name='outil',
            name='narration_langue',
            field=models.ManyToManyField(to='bdmultimedia.LangueNarration', verbose_name='Langue de la narration'),
        ),
        migrations.AddField(
            model_name='outil',
            name='sous_titre',
            field=models.ManyToManyField(to='bdmultimedia.SousTitre', verbose_name='Sous-titrage'),
        ),
    ]
