# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0069_auto_20180208_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='audiodescription',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='language_des_signes',
        ),
        migrations.AddField(
            model_name='outil',
            name='malvoyants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='Cet outil est-il accessible aux malvoyants (audiodescription)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='malentendants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='Cet outil est-il accessible aux malentendants (Sous titraage, language des signes)'),
        ),
    ]
