# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0070_auto_20180208_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='autre_elements_socio',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_experiences_musicales',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_materiau_musical',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_pratique_musicale',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_solicitation_autre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_solicitation_musicale',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='elements_socio',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='experiences_musicales',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='liste_elements_socio',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='liste_experiences',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='liste_materiau',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='liste_pratiques',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='pratique_musicale',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='solicitation_autre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='solicitation_musicale',
        ),
        migrations.AlterField(
            model_name='outil',
            name='materiau_musical',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='Parle-t-on du mat\xe9riau musical?'),
        ),
        migrations.DeleteModel(
            name='ElemMus',
        ),
        migrations.DeleteModel(
            name='ElemSocio',
        ),
        migrations.DeleteModel(
            name='ExpMus',
        ),
        migrations.DeleteModel(
            name='PratMus',
        ),
    ]
