# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0071_auto_20180211_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Genre musical',
            },
        ),
        migrations.CreateModel(
            name='LanguageMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Language musical',
            },
        ),
        migrations.CreateModel(
            name='Orchestration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Son et orchestration',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Structure',
            },
        ),
        migrations.CreateModel(
            name='StyleMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Style musical',
            },
        ),
        migrations.AddField(
            model_name='outil',
            name='genre_musical',
            field=models.ManyToManyField(to='bdmultimedia.GenreMusical', verbose_name='Parle-t-on du genre musical, si oui pr\xe9cisez.'),
        ),
        migrations.AddField(
            model_name='outil',
            name='language_musical',
            field=models.ManyToManyField(to='bdmultimedia.LanguageMusical', verbose_name='Parle-t-on du language musical, si oui pr\xe9cisez.'),
        ),
        migrations.AddField(
            model_name='outil',
            name='orchestration',
            field=models.ManyToManyField(to='bdmultimedia.Orchestration', verbose_name="Parle-t-on du son et de l'orchestration, si oui pr\xe9cisez."),
        ),
        migrations.AddField(
            model_name='outil',
            name='structure',
            field=models.ManyToManyField(to='bdmultimedia.Structure', verbose_name='Parle-t-on de la structure, si oui pr\xe9cisez.'),
        ),
        migrations.AddField(
            model_name='outil',
            name='style_musical',
            field=models.ManyToManyField(to='bdmultimedia.StyleMusical', verbose_name='Parle-t-on du style musical, si oui pr\xe9cisez.'),
        ),
    ]
