# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0072_auto_20180211_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceMusicale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Experiences musical',
            },
        ),
        migrations.AlterModelOptions(
            name='genremusical',
            options={'verbose_name': 'Genres musical'},
        ),
        migrations.AlterModelOptions(
            name='languagemusical',
            options={'verbose_name': 'Languages musical'},
        ),
        migrations.AlterModelOptions(
            name='orchestration',
            options={'verbose_name': 'Sons et orchestration'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Structures'},
        ),
        migrations.AlterModelOptions(
            name='stylemusical',
            options={'verbose_name': 'Styles musical'},
        ),
        migrations.AddField(
            model_name='outil',
            name='experience_musicale',
            field=models.ManyToManyField(to='bdmultimedia.ExperienceMusicale', verbose_name="Parle-t-on de l'experience musicale, si oui pr\xe9cisez."),
        ),
    ]
