# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0073_auto_20180211_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contexte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Contexte de composition, cr\xe9ation, interpr\xe9tation...',
            },
        ),
        migrations.CreateModel(
            name='RoleEvolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'R\xf4le et \xe9volution',
            },
        ),
        migrations.AddField(
            model_name='outil',
            name='elements_socioculturels',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', help_text='Si non, passez \xe0 la question U.28', max_length=200, verbose_name='Parle-t-on des \xe9l\xe9ments socioculturels et historiques?'),
        ),
        migrations.AddField(
            model_name='outil',
            name='epoque',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Avant le XII\xe8', 'Avant le XII\xe8'), ('XII\xe8', 'XII\xe8'), ('XIII\xe8', 'XIII\xe8'), ('XIV\xe8', 'XIV\xe8'), ('XV\xe8', 'XV\xe8'), ('XVI\xe8', 'XVI\xe8'), ('XVII\xe8', 'XVII\xe8'), ('XVIII\xe8', 'XVIII\xe8'), ('XIX\xe8', 'XIX\xe8'), ('XX\xe8', 'XX\xe8'), ('XXI\xe8', 'XXI\xe8')], max_length=50, null=True, verbose_name='\xc9poque'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='materiau_musical',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', help_text='Si non, passez \xe0 la question M.26', max_length=200, verbose_name='Parle-t-on du mat\xe9riau musical?'),
        ),
        migrations.AddField(
            model_name='outil',
            name='contexte',
            field=models.ManyToManyField(to='bdmultimedia.Contexte', verbose_name="Parle-t-on du contexte de composition, cr\xe9ation, interpr\xe9tation de l'oeuvre, de l'instrument..."),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_evolution',
            field=models.ManyToManyField(to='bdmultimedia.RoleEvolution', verbose_name="Parle-t-on du r\xf4le et de l'\xe9volution du"),
        ),
    ]
