# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0074_auto_20180211_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SollicitationGenerale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Sollicitation g\xe9n\xe9rale',
            },
        ),
        migrations.CreateModel(
            name='SollicitationMusicale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Sollicitation musicale',
            },
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_sonore_valeur',
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='Temps de musique seule (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus_par',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='Temps de parole et musique superpos\xe9es (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_par',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='Temps de parole seule (hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='outil',
            name='sollicitation_generale',
            field=models.ManyToManyField(to='bdmultimedia.SollicitationGenerale', verbose_name="En g\xe9n\xe9ral (hors musique) comment sollicite-t-on l'usager?"),
        ),
        migrations.AddField(
            model_name='outil',
            name='sollicitation_musicale',
            field=models.ManyToManyField(to='bdmultimedia.SollicitationMusicale', verbose_name="Comment sollicite-t-on musicalement l'usager?"),
        ),
    ]
