# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0075_auto_20180211_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='commentaire_nombre',
            field=models.PositiveIntegerField(blank=True, help_text='Laisser vide si les commentaires sont impossibles', null=True, verbose_name='R.16 Nombre de commentaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='commentaire_possible',
            field=models.BooleanField(verbose_name='R.15 Possibilit\xe9 de laisser des commentaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='contexte',
            field=models.ManyToManyField(to='bdmultimedia.Contexte', verbose_name="M.27.2 Parle-t-on du contexte de composition, cr\xe9ation, interpr\xe9tation de l'oeuvre, de l'instrument..."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='depouillement_date',
            field=models.DateField(blank=True, null=True, verbose_name='R.12 Date du d\xe9pouillement'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='deuxieme_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas car l'outil \xe9tait disponible sur la page d'accueil"), ("On peut consulter l'outil directement sur cette deuxi\xe8me page", "On peut consulter l'outil directement sur cette deuxi\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ("Le nom de l'outil lui m\xeame", "Le nom de l'outil lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format de l'outil dont il s'agit", "Est relatif au format de l'outil dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name="S.18 Quel est le DEUXIEME onglet \xe0 ouvrir pour trouver l'outil?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='duree',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='R.9 Dur\xe9e'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='elements_socioculturels',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='M.27 Parle-t-on des \xe9l\xe9ments socioculturels et historiques?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='ensemble_thematique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=4, verbose_name="R.3.1 Cet outil fait-il partie d'un ensemble th\xe9matique du m\xeame type? (regroup\xe9 par l'organisme producteur)"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='ensemble_thematique_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='R.3.2 Si oui, quel est le nom de cet ensemble?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='epoque',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Avant le XII\xe8', 'Avant le XII\xe8'), ('XII\xe8', 'XII\xe8'), ('XIII\xe8', 'XIII\xe8'), ('XIV\xe8', 'XIV\xe8'), ('XV\xe8', 'XV\xe8'), ('XVI\xe8', 'XVI\xe8'), ('XVII\xe8', 'XVII\xe8'), ('XVIII\xe8', 'XVIII\xe8'), ('XIX\xe8', 'XIX\xe8'), ('XX\xe8', 'XX\xe8'), ('XXI\xe8', 'XXI\xe8')], max_length=50, null=True, verbose_name='M.27.1 \xc9poque'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_graphique',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Repr\xe9sentation graphique traditionnelle (partition + notes)', 'Repr\xe9sentation graphique traditionnelle (partition + notes)'), ("Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)", "Repr\xe9sentation graphique traditionnelle augment\xe9e (Ex. les notes s'\xe9clairent quand on les entends)"), ('Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)', 'Repr\xe9sentation graphique traditionelle illustr\xe9e (Ex. les notes sont en fait des oiseaux sur les lignes de la port\xe9e)'), ('Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)', 'Repr\xe9sentation graphique sch\xe9matis\xe9e (Ex. il y toujours un port\xe9e mais ce sont des courbes qui figurent la m\xe9lodie)'), ('Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es; cf. ratatouille!!)', 'Repr\xe9sentation graphique symbolis\xe9e (Ex. des images anim\xe9es; cf. ratatouille!!)'), ('Autre', 'Autre')], max_length=482, verbose_name='EM.34 \xc9vocation graphique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_litteraire',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Texte oral', 'Texte oral'), ('Texte \xe9crit', 'Texte \xe9crit'), ('Autre', 'Autre')], max_length=200, verbose_name='EM.36 \xc9vocation litt\xe9raire'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_plastique',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Sculpture', 'Sculpture'), ('Installation', 'Installation'), ('Autre', 'Autre')], max_length=200, verbose_name='EM.35 \xc9vocation plastique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='experience_musicale',
            field=models.ManyToManyField(to='bdmultimedia.ExperienceMusicale', verbose_name="M.26 Parle-t-on de l'experience musicale, si oui pr\xe9cisez."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='format',
            field=models.ManyToManyField(to='bdmultimedia.FormatOutil', verbose_name="R.7 Format de l'outil"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='forme_narrative',
            field=models.ManyToManyField(to='bdmultimedia.FormeNarrative', verbose_name='R.8 Forme narrative g\xe9n\xe9rale'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='genre_musical',
            field=models.ManyToManyField(to='bdmultimedia.GenreMusical', verbose_name='M.25.4 Parle-t-on du genre musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='interface',
            field=models.CharField(choices=[('Simple consultation', 'Simple consultation'), ('Participation limit\xe9e', "Participation limit\xe9e (l'usager est actif mais se contente de r\xe9pondre aux consignes)"), ('Participation dynamique', "Participation dynamique (l'usager co-construit le service)"), ('Autre', 'Autre')], max_length=200, null=True, verbose_name="R.13 Que permet l'interface?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='language_musical',
            field=models.ManyToManyField(to='bdmultimedia.LanguageMusical', verbose_name='M.25.3 Parle-t-on du language musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='malentendants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='S.24.1 Cet outil est-il accessible aux malentendants (Sous titraage, language des signes)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='malvoyants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='S.24.2 Cet outil est-il accessible aux malvoyants (audiodescription)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='materiau_musical',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='M.25 Parle-t-on du mat\xe9riau musical?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mise_en_ligne_date',
            field=models.DateField(blank=True, help_text='laisser vide si non disponible', null=True, verbose_name='R.11 Date de la mise en ligne'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mode_consultation',
            field=models.ManyToManyField(to='bdmultimedia.ModeConsultation', verbose_name='S.21 Mode de consultation offert au public'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mode_hebergement',
            field=models.ManyToManyField(to='bdmultimedia.ModeHebergement', verbose_name="S.20 Mode d'h\xe9bergement sur la toile"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='narration_langue',
            field=models.ManyToManyField(to='bdmultimedia.LangueNarration', verbose_name='S.22 Langue de la narration'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pages',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='R.10 Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='orchestration',
            field=models.ManyToManyField(to='bdmultimedia.Orchestration', verbose_name="M.25.1 Parle-t-on du son et de l'orchestration, si oui pr\xe9cisez."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='personnification_service',
            field=models.CharField(choices=[('Service g\xe9n\xe9rique', 'Service g\xe9n\xe9rique'), ('Service sp\xe9cialis\xe9', 'Service sp\xe9cialis\xe9 (public cat\xe9goris\xe9)'), ('Service personnalis\xe9 et/ou individualis\xe9', 'Service personnalis\xe9 et/ou individualis\xe9'), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='R.14 Degr\xe9s de personnification du service'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='premier_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas"), ("Disponible et consultable sur la page d'acc\xe8s", "L'outil est disponible et consultable sur la page d'acc\xe8s"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ("Le nom de l'outil lui m\xeame", "Le nom de l'outil lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format de l'outil dont il s'agit", "Est relatif au format de l'outil dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name="S.17 Quel est le PREMIER onglet \xe0 ouvrir pour trouver l'outil?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_nom',
            field=models.CharField(max_length=200, verbose_name='R.5Pr\xe9ciser le nom complet du/des producteur(s)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_type',
            field=models.ManyToManyField(to='bdmultimedia.ProdType', verbose_name='R.4 Qui est le producteur de cet outil?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_evolution',
            field=models.ManyToManyField(to='bdmultimedia.RoleEvolution', verbose_name="M.27.3 Parle-t-on du r\xf4le et de l'\xe9volution du"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.URLField(help_text='ex. site de la Philharmonie de Paris', verbose_name="R.3 Chemin d'acc\xe8s au site d'h\xe9bergement"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sollicitation_generale',
            field=models.ManyToManyField(to='bdmultimedia.SollicitationGenerale', verbose_name="U.29 En g\xe9n\xe9ral (hors musique) comment sollicite-t-on l'usager?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sollicitation_musicale',
            field=models.ManyToManyField(to='bdmultimedia.SollicitationMusicale', verbose_name="U.28 Comment sollicite-t-on musicalement l'usager?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sonore_valeur',
            field=models.CharField(choices=[('Nsp', "Ne s'applique pas"), ('Premier plan', 'Premier Plan'), ('Arri\xe8re plan', 'Arri\xe8re plan'), ('Alternance', 'Alternance')], default='Nsp', max_length=200, verbose_name='PM.33 Mise en valeur du sonore'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sous_titre',
            field=models.ManyToManyField(to='bdmultimedia.SousTitre', verbose_name='S.23 Sous-titrage'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='structure',
            field=models.ManyToManyField(to='bdmultimedia.Structure', verbose_name='M.25.2 Parle-t-on de la structure, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='style_musical',
            field=models.ManyToManyField(to='bdmultimedia.StyleMusical', verbose_name='M.25.5 Parle-t-on du style musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='support_diffusion',
            field=models.ManyToManyField(to='bdmultimedia.SupportDiffusion', verbose_name='R.6 Support de diffusion'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='PM.30 Temps de musique seule (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_mus_par',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='PM.32 Temps de parole et musique superpos\xe9es (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='temps_par',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas", max_length=8, verbose_name='PM.31 Temps de parole seule (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='titre',
            field=models.CharField(max_length=200, verbose_name="R.1 Titre de l'outil"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='troisieme_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page"), ("On peut consulter l'outil directement sur cette troisi\xe8me page", "On peut consulter l'outil directement sur cette trois\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ("Le nom de l'outil lui m\xeame", "Le nom de l'outil lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format de l'outil dont il s'agit", "Est relatif au format de l'outil dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name="S.19 Quel est le TROISIEME onglet \xe0 ouvrir pour trouver l'outil?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='url',
            field=models.CharField(help_text="Dernier URL \xe0 suivre pour ateindre l'outil - nsp = ne s'applique pas", max_length=200, unique=True, verbose_name="R.2 Chemin d'acc\xe8s direct"),
        ),
    ]
