# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0076_auto_20180211_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvocationAutre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': "\xc9vocations d'autre discipline",
            },
        ),
        migrations.CreateModel(
            name='EvocationGraphique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': '\xc9vocations graphique',
            },
        ),
        migrations.CreateModel(
            name='EvocationPlastique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': '\xc9vocations plastique',
            },
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_evocation_autre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_evocation_graphique',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_evocation_litteraire',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='autre_evocation_plastique',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='evocation_autre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='evocation_graphique',
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_litteraire',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Texte oral', 'Texte oral'), ('Texte \xe9crit', 'Texte \xe9crit')], max_length=200, verbose_name='EM.36 \xc9vocation litt\xe9raire'),
        ),
        migrations.RemoveField(
            model_name='outil',
            name='evocation_plastique',
        ),
        migrations.AddField(
            model_name='outil',
            name='evocation_autre',
            field=models.ManyToManyField(to='bdmultimedia.EvocationAutre', verbose_name='Autres disciplines \xe9voqu\xe9es'),
        ),
        migrations.AddField(
            model_name='outil',
            name='evocation_graphique',
            field=models.ManyToManyField(to='bdmultimedia.EvocationGraphique', verbose_name='EM.34 \xc9vocation graphique'),
        ),
        migrations.AddField(
            model_name='outil',
            name='evocation_plastique',
            field=models.ManyToManyField(to='bdmultimedia.EvocationPlastique', verbose_name='EM.35 \xc9vocation plastique'),
        ),
    ]
