# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0078_auto_20180211_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHomme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des personnages',
            },
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_humain_femme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_humain_neutre',
        ),
        migrations.AddField(
            model_name='outil',
            name='humain',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, verbose_name='St\xe9.39 Y-a-t-il des humains (compter les personnes qui ont un r\xf4le dans la narration, qui sont maximum 3 dans le champ ou plein cadre)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='exemples_notions_interdisciplinaires',
            field=models.ManyToManyField(to='bdmultimedia.NotionsInter', verbose_name='I.39 Donner des exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_concepts',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Nsp', "Ne s'applique pas")], default='Nsp', max_length=50, verbose_name='I.38 \xc0 partir de quelle notion? - Notions communes (luminosit\xe9, transparence, vitesse, mouvement)'),
        ),
        migrations.RemoveField(
            model_name='outil',
            name='notion_experiences',
        ),
        migrations.AddField(
            model_name='outil',
            name='notion_experiences',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Nsp', "Ne s'applique pas")], default='Nsp', max_length=50, verbose_name='I.38 \xc0 partir de quelle notion? - Exp\xe9rience (\xe9motions)'),
        ),
        migrations.RemoveField(
            model_name='outil',
            name='notion_pratiques',
        ),
        migrations.AddField(
            model_name='outil',
            name='notion_pratiques',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Nsp', "Ne s'applique pas")], default='Nsp', max_length=50, verbose_name='I.38 \xc0 partir de quelle notion? - Pratique (processus de cr\xe9ation)'),
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_humain_homme',
        ),
        migrations.AddField(
            model_name='outil',
            name='role_humain_homme',
            field=models.ManyToManyField(to='bdmultimedia.RoleHomme', verbose_name='R\xf4le des hommes'),
        ),
    ]
