# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0080_auto_20180211_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='nb_obj_anime_femmes',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='nb_obj_anime_hommes',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='nb_obj_anime_indetermines',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='nb_obj_anime_total',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='nb_pers_fictifs_femmes',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='nb_pers_fictifs_hommes',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='nb_pers_fictifs_indetermines',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='nb_pers_fictifs_total',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_obj_anime_femme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_obj_anime_homme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_obj_anime_neutre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_pers_fictif_femme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_pers_fictif_homme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_pers_fictif_neutre',
        ),
        migrations.AddField(
            model_name='outil',
            name='animaux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, verbose_name='St\xe9.41 Y-a-t-il des animaux?'),
        ),
        migrations.AddField(
            model_name='outil',
            name='instr_anime',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, verbose_name='St\xe9.42 Y-a-t-il des instruments anim\xe9s'),
        ),
        migrations.AddField(
            model_name='outil',
            name='pers_anime',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, verbose_name='St\xe9.40 Y-a-t-il des personnages anim\xe9s?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='humain',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, verbose_name='St\xe9.39 Y-a-t-il des humains? (compter les personnes qui ont un r\xf4le dans la narration, qui sont maximum 3 dans le champ ou plein cadre)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_femmes',
            field=models.PositiveIntegerField(default=0, verbose_name='St\xe9.39.1 Nombre de femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_hommes',
            field=models.PositiveIntegerField(default=0, verbose_name="St\xe9.39.1 Nombre d'hommes"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_humains_indetermines',
            field=models.PositiveIntegerField(default=0, verbose_name="St\xe9.39.1 Nombre d'humains au genre ind\xe9termin\xe9"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_humains_total',
            field=models.PositiveIntegerField(default=0, verbose_name="St\xe9.39.1 Nombre d'humains total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_femmes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe940.1 Nombre de personnages anim\xe9s femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_hommes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe940.1 Nombre de personnages anim\xe9s hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_indetermines',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe940.1 Nombre de personnages anim\xe9s au genre ind\xe9termin\xe9'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_total',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe940.1 Nombre de personnages anim\xe9s total'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_femme',
            field=models.ManyToManyField(to='bdmultimedia.RoleFemmes', verbose_name='St\xe9.39.2 R\xf4le des femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_homme',
            field=models.ManyToManyField(to='bdmultimedia.RoleHomme', verbose_name='St\xe9.39.3 R\xf4le des hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_neutre',
            field=models.ManyToManyField(to='bdmultimedia.RoleHumainNeutre', verbose_name='St\xe9.39.4 R\xf4le des indetermin\xe9s'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_femme',
            field=models.CharField(max_length=200, verbose_name='St\xe940.3 R\xf4le des personnages anim\xe9s femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_homme',
            field=models.CharField(max_length=200, verbose_name='St\xe940.2 R\xf4le des personnages anim\xe9s hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_neutre',
            field=models.CharField(max_length=200, verbose_name='St\xe940.4 R\xf4le des personnages anim\xe9s neutres'),
        ),
    ]
