# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0081_auto_20180211_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAnimauxFemmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des femmes',
            },
        ),
        migrations.CreateModel(
            name='RoleAnimauxHomme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des hommes',
            },
        ),
        migrations.CreateModel(
            name='RoleAnimauxNeutre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des humain neutre',
            },
        ),
        migrations.CreateModel(
            name='RoleInstrFemmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des femmes',
            },
        ),
        migrations.CreateModel(
            name='RoleInstrHomme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des hommes',
            },
        ),
        migrations.CreateModel(
            name='RoleInstrNeutre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des humain neutre',
            },
        ),
        migrations.CreateModel(
            name='RolePersAnimFemmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des femmes',
            },
        ),
        migrations.CreateModel(
            name='RolePersAnimHomme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des hommes',
            },
        ),
        migrations.CreateModel(
            name='RolePersAnimNeutre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Role des humain neutre',
            },
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_animaux_femme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_animaux_homme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_animaux_neutre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_instr_anime_femme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_instr_anime_homme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_instr_anime_neutre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_pers_anime_femme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_pers_anime_homme',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='role_pers_anime_neutre',
        ),
        migrations.AddField(
            model_name='outil',
            name='role_animaux_femme',
            field=models.ManyToManyField(to='bdmultimedia.RoleAnimauxFemmes', verbose_name='R\xf4le des animaux femelles'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_animaux_homme',
            field=models.ManyToManyField(to='bdmultimedia.RoleAnimauxHomme', verbose_name='R\xf4le des animaux m\xe2les'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_animaux_neutre',
            field=models.ManyToManyField(to='bdmultimedia.RoleAnimauxNeutre', verbose_name='R\xf4le des animaux neutres'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_instr_anime_femme',
            field=models.ManyToManyField(to='bdmultimedia.RoleInstrFemmes', verbose_name='R\xf4le des instruments anthropomorphes f\xe9minins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_instr_anime_homme',
            field=models.ManyToManyField(to='bdmultimedia.RoleInstrHomme', verbose_name='R\xf4le des instruments anthropomorphes masculins'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_instr_anime_neutre',
            field=models.ManyToManyField(to='bdmultimedia.RoleInstrNeutre', verbose_name='R\xf4le des instruments anthropomorphes neutres'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_anime_femme',
            field=models.ManyToManyField(to='bdmultimedia.RolePersAnimFemmes', verbose_name='St\xe940.3 R\xf4le des personnages anim\xe9s femmes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_anime_homme',
            field=models.ManyToManyField(to='bdmultimedia.RolePersAnimHomme', verbose_name='St\xe940.2 R\xf4le des personnages anim\xe9s hommes'),
        ),
        migrations.AddField(
            model_name='outil',
            name='role_pers_anime_neutre',
            field=models.ManyToManyField(to='bdmultimedia.RolePersAnimNeutre', verbose_name='St\xe940.4 R\xf4le des personnages anim\xe9s neutres'),
        ),
    ]
