# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0082_auto_20180211_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='exemples_notions_interdisciplinaires',
            field=models.ManyToManyField(blank=True, to='bdmultimedia.NotionsInter', verbose_name='I.39 Donner des exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_animaux_indetermines',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name="St\xe9.41.1 Nombre d'animaux au genre ind\xe9termin\xe9"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_animaux_total',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name="St\xe9.41.1 Nombre d'animaux total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_femelles',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe9.41.1 Nombre de femelles'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_femmes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s f\xe9minins"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_hommes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s masculins"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_indetermines',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s au genre ind\xe9termin\xe9"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_total',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_males',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe9.41.1 Nombre de m\xe2les'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_femmes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe9.40.1 Nombre de personnages anim\xe9s femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_hommes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe9.40.1 Nombre de personnages anim\xe9s hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_indetermines',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe9.40.1 Nombre de personnages anim\xe9s au genre ind\xe9termin\xe9'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_total',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='St\xe9.40.1 Nombre de personnages anim\xe9s total'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_femme',
            field=models.ManyToManyField(to='bdmultimedia.RoleAnimauxFemmes', verbose_name='St\xe9.41.3 R\xf4le des animaux femelles'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_homme',
            field=models.ManyToManyField(to='bdmultimedia.RoleAnimauxHomme', verbose_name='St\xe9.41.2 R\xf4le des animaux m\xe2les'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_neutre',
            field=models.ManyToManyField(to='bdmultimedia.RoleAnimauxNeutre', verbose_name='St\xe9.41.4 R\xf4le des animaux neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_femme',
            field=models.ManyToManyField(to='bdmultimedia.RoleInstrFemmes', verbose_name='St\xe9.42.3 R\xf4le des instruments anthropomorphes f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_homme',
            field=models.ManyToManyField(to='bdmultimedia.RoleInstrHomme', verbose_name='St\xe9.42.2 R\xf4le des instruments anthropomorphes masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_neutre',
            field=models.ManyToManyField(to='bdmultimedia.RoleInstrNeutre', verbose_name='St\xe9.42.4 R\xf4le des instruments anthropomorphes neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_femme',
            field=models.ManyToManyField(to='bdmultimedia.RolePersAnimFemmes', verbose_name='St\xe9.40.3 R\xf4le des personnages anim\xe9s femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_homme',
            field=models.ManyToManyField(to='bdmultimedia.RolePersAnimHomme', verbose_name='St\xe9.40.2 R\xf4le des personnages anim\xe9s hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_neutre',
            field=models.ManyToManyField(to='bdmultimedia.RolePersAnimNeutre', verbose_name='St\xe9.40.4 R\xf4le des personnages anim\xe9s neutres'),
        ),
    ]
