# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0084_auto_20180211_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotConcept',
        ),
        migrations.DeleteModel(
            name='NotExp',
        ),
        migrations.DeleteModel(
            name='NotPratique',
        ),
    ]
