# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0085_auto_20180211_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='producteur_nom',
            field=models.CharField(max_length=200, verbose_name='R.5 Pr\xe9ciser le nom complet du/des producteur(s)'),
        ),
    ]
