# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0089_auto_20180215_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='malentendants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='S.24.1 Cet outil est-il accessible aux malentendants (Sous titrage, language des signes)'),
        ),
    ]
