# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0090_auto_20180226_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='image',
            field=models.ImageField(null=True, upload_to='.', verbose_name="Capture d'\xe9cran"),
        ),
    ]
