# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0091_outil_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soustitre',
            options={'verbose_name': 'Sous-titre'},
        ),
    ]
