# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0092_auto_20180307_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.', verbose_name="Capture d'\xe9cran"),
        ),
    ]
