# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0093_auto_20180307_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleanimauxfemmes',
            options={'verbose_name': 'Role des femelle'},
        ),
        migrations.AlterModelOptions(
            name='roleanimauxhomme',
            options={'verbose_name': 'Role des male'},
        ),
        migrations.AlterModelOptions(
            name='roleanimauxneutre',
            options={'verbose_name': 'Role des animaux ind\xe9termin\xe9'},
        ),
        migrations.AlterModelOptions(
            name='rolefemmes',
            options={'verbose_name': 'Role des femme'},
        ),
        migrations.AlterModelOptions(
            name='rolehomme',
            options={'verbose_name': 'Role des homme'},
        ),
        migrations.AlterModelOptions(
            name='rolehumainneutre',
            options={'verbose_name': 'Role des humain ind\xe9termin\xe9'},
        ),
        migrations.AlterModelOptions(
            name='roleinstrfemmes',
            options={'verbose_name': 'Role des instruments femme'},
        ),
        migrations.AlterModelOptions(
            name='roleinstrhomme',
            options={'verbose_name': 'Role des instruments homme'},
        ),
        migrations.AlterModelOptions(
            name='roleinstrneutre',
            options={'verbose_name': 'Role des instruments ind\xe9termin\xe9'},
        ),
        migrations.AlterModelOptions(
            name='rolepersanimfemmes',
            options={'verbose_name': 'Role des personnages anim\xe9s femme'},
        ),
        migrations.AlterModelOptions(
            name='rolepersanimhomme',
            options={'verbose_name': 'Role des personnages anim\xe9s homme'},
        ),
        migrations.AlterModelOptions(
            name='rolepersanimneutre',
            options={'verbose_name': 'Role des personnages anim\xe9s ind\xe9termin\xe9'},
        ),
    ]
