# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0094_auto_20180307_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='image',
        ),
    ]
