# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bdmultimedia', '0095_remove_outil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='cree_par',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
