# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0096_outil_cree_par'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outil',
            old_name='cree_par',
            new_name='utilisateur',
        ),
    ]
