# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0097_auto_20180313_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='integration',
            field=models.TextField(blank=True, verbose_name="code pour l'integration de l'outil"),
        ),
    ]
