# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0098_outil_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='integration',
            field=models.TextField(blank=True, verbose_name="code pour l'integration de l'outil (si applicable)"),
        ),
    ]
