# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-30 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0101_auto_20180330_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='interface_autre',
        ),
        migrations.RemoveField(
            model_name='outil',
            name='personnification_autre',
        ),
        migrations.AlterField(
            model_name='outil',
            name='commentaire_nombre',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='R.16 Nombre de commentaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='deuxieme_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas car l'outil \xe9tait disponible sur la page d'accueil"), ("On peut consulter l'outil directement sur cette deuxi\xe8me page", "On peut consulter l'outil directement sur cette deuxi\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.18 Quel est le DEUXIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='ensemble_thematique_nom',
            field=models.CharField(blank=True, help_text='Ex: Camille raconte', max_length=200, verbose_name='R.3.2 Si oui, sous quel titre est regroup\xe9 cet ensemble?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='forme_narrative',
            field=models.ManyToManyField(to='bdmultimedia.FormeNarrative', verbose_name='R.8 Formes narratives'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='interface',
            field=models.CharField(choices=[('Simple consultation', 'Simple consultation'), ('Participation limit\xe9e', "Participation limit\xe9e (l'usager est actif mais se contente de r\xe9pondre aux consignes)"), ('Participation dynamique', "Participation dynamique (l'usager co-construit le service)")], max_length=200, null=True, verbose_name="R.13 Que permet l'interface?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='malentendants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='S.24.1 Ce dispositif est-il int\xe9gralement accessible aux malentendants (Sous titrage, language des signes)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='malvoyants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='S.24.2 Ce dispositif est-il int\xe9gralement accessible aux malvoyants (audiodescription)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pages',
            field=models.PositiveIntegerField(default=0, help_text='Correspond au nombre de page web sur lesquelles se de\u0301cline le  dispositif .', null=True, verbose_name='R.10 Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='personnification_service',
            field=models.CharField(choices=[('Service g\xe9n\xe9rique', 'Service g\xe9n\xe9rique'), ('Service sp\xe9cialis\xe9', 'Service sp\xe9cialis\xe9 (public cat\xe9goris\xe9)'), ('Service personnalis\xe9 et/ou individualis\xe9', 'Service personnalis\xe9 et/ou individualis\xe9')], max_length=200, null=True, verbose_name='R.14 Degr\xe9s de personnification du service'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='premier_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas"), ("Disponible et consultable sur la page d'acc\xe8s", "L'outil est disponible et consultable sur la page d'acc\xe8s"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.17 Quel est le PREMIER onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.URLField(help_text='ex. site de la Philharmonie de Paris', verbose_name="R.3 URL d'acc\xe8s au site d'h\xe9bergement"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='troisieme_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page"), ("On peut consulter l'outil directement sur cette troisi\xe8me page", "On peut consulter l'outil directement sur cette trois\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.19 Quel est le TROISIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='url',
            field=models.CharField(help_text="Dernier URL \xe0 suivre pour ateindre l'outil - nsp = ne s'applique pas", max_length=200, unique=True, verbose_name="R.2 URL d'acc\xe8s direct"),
        ),
    ]
