# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0104_auto_20180503_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='materiel_imprimer',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=200, null=True, verbose_name='R.13.1 Le dispositif comprend-il du mat\xe9riel \xe0 imprimer (ex. livret en pdf) ?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='duree',
            field=models.CharField(default='00:00:00', help_text="nsp = ne s'applique pas, ddv = dur\xe9e d\u2019\xe9coute variable. La dur\xe9e d\u2019\xe9coute est variable puisque les utilisateurs peuvent d\xe9cider, ou non, de regarder les vid\xe9os. Concerne les dispositifs qui allient texte et vid\xe9o.", max_length=8, verbose_name='R.9 Dur\xe9e'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mise_en_ligne_date',
            field=models.DateField(blank=True, help_text='Si seule l\u2019ann\xe9e de mise en ligne est disponible entrer la date de mise en ligne au 1er janvier de l\u2019ann\xe9e concern\xe9e', null=True, verbose_name='R.11 Date de la mise en ligne'),
        ),
    ]
