# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0107_auto_20180504_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='narration_langue',
            field=models.ManyToManyField(to='bdmultimedia.LangueNarration', verbose_name='S.22 Langue du dispositif'),
        ),
        migrations.RemoveField(
            model_name='outil',
            name='producteur_nom',
        ),
        migrations.AddField(
            model_name='outil',
            name='producteur_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='R.5 Pr\xe9ciser le nom complet du/des producteur(s)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sous_titre',
            field=models.ManyToManyField(help_text='Les sous-titrages automatiques propos\xe9s par YouTube n\u2019entrent pas en consid\xe9ration.', to='bdmultimedia.SousTitre', verbose_name='S.23 Sous-titrage'),
        ),
    ]
