# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0108_auto_20180504_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='commentaire_possible',
            field=models.BooleanField(help_text='Compter les commentaires qui apparaissent sur la page de consultation du dispositif (ex. Si il n\u2019y a pas de possibilit\xe9 de commentaire sur les capsules de l\u2019OSM mais que les commentaires sont possibles sur l\u2019h\xe9bergement youtube ne pas cocher)', verbose_name='R.15 Possibilit\xe9 de laisser des commentaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='contexte',
            field=models.ManyToManyField(help_text='Si il est juste fait mention d\u2019une date sans donner plus d\u2019information sur ce qui se passait \xe0 l\u2019\xe9poque cocher \u201cNon\u201d.', to='bdmultimedia.Contexte', verbose_name="M.27.2 Parle-t-on du contexte de composition, cr\xe9ation, interpr\xe9tation de l'oeuvre, de l'instrument..."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='ensemble_thematique_nom',
            field=models.CharField(blank=True, help_text='Ex: Camille raconte', max_length=200, verbose_name='R.3.2 Si oui, donnez le titre sous lequel est regroup\xe9 cet ensemble.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='materiau_musical',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', help_text='Registres (au sens de groupe de hauteur si cela concerne les registres de l\u2019orgue cocher \xab timbres \xbb)', max_length=200, verbose_name='M.25 Parle-t-on du mat\xe9riau musical?'),
        ),
    ]
