# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0109_auto_20180507_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='page_outil',
            field=models.BooleanField(default=False, verbose_name="Afficher directement une page qui fait office d'outil"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.URLField(help_text='Attention, enlever la barre oblique \xab / \xbb \xe0 la fin de l\u2019URL www.osm.ca. <br> Si le dispositif est une vid\xe9o d\u2019un-e YouTubeur-e, indiquer le lien vers sa cha\xeene YouTube.', verbose_name="R.3 URL d'acc\xe8s au site d'h\xe9bergement"),
        ),
    ]
