# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 19:47
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0111_auto_20180507_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='epoque',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Avant le XII\xe8', 'Avant le XII\xe8'), ('XII\xe8', 'XII\xe8'), ('XIII\xe8', 'XIII\xe8'), ('XIV\xe8', 'XIV\xe8'), ('XV\xe8', 'XV\xe8'), ('XVI\xe8', 'XVI\xe8'), ('XVII\xe8', 'XVII\xe8'), ('XVIII\xe8', 'XVIII\xe8'), ('XIX\xe8', 'XIX\xe8'), ('XX\xe8', 'XX\xe8'), ('XXI\xe8', 'XXI\xe8'), ('nsp', 'nsp')], max_length=100, null=True, verbose_name='M.27.1 \xc9poque'),
        ),
    ]
