# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0115_auto_20180511_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='producteur_nom',
        ),
        migrations.AddField(
            model_name='outil',
            name='producteur_nom',
            field=models.ManyToManyField(to='bdmultimedia.ProducteurNom', verbose_name='R.5 Pr\xe9ciser le nom complet du/des producteur(s)'),
        ),
    ]
