# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0122_auto_20180515_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_total',
            field=models.CharField(help_text='Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=50, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s total"),
        ),
    ]
