# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0123_auto_20180515_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='nb_humains_total',
            field=models.CharField(default='0', help_text='On compte tous les humains qui sont 3 ou moins dans le cadre. Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=50, verbose_name="St\xe9.39.1 Nombre d'humains total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_total',
            field=models.CharField(help_text='cf. anthropomorphe. Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=50, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s total"),
        ),
    ]
