# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0126_auto_20180517_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='deuxieme_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas car l'outil \xe9tait disponible sur la page d'accueil"), ("On peut consulter l'outil directement sur cette deuxi\xe8me page", "On peut consulter l'outil directement sur cette deuxi\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.18 Quel est le DEUXIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_autre',
            field=models.ManyToManyField(to='bdmultimedia.EvocationAutre', verbose_name='I.37 Interdisciplinarit\xe9'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='interface',
            field=models.CharField(choices=[('Simple consultation', 'Simple consultation'), ('Participation limit\xe9e', "Participation limit\xe9e (l'usager est actif mais se contente de r\xe9pondre aux consignes)"), ('Participation dynamique', "Participation dynamique (l'usager co-construit le service)")], max_length=200, null=True, verbose_name='R.13 Interactivit\xe9'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='materiau_musical',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=200, verbose_name='M.25 Parle-t-on du mat\xe9riau musical?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mise_en_ligne_date',
            field=models.DateField(blank=True, help_text='Si seule l\u2019ann\xe9e de mise en ligne est disponible entrer la date de mise en ligne au 1er janvier de l\u2019ann\xe9e concern\xe9e', null=True, verbose_name='R.11 Date de la mise en ligne'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='orchestration',
            field=models.ManyToManyField(help_text='Registres (au sens de groupe de hauteur si cela concerne les registres de l\u2019orgue cocher \xab timbres \xbb)', to='bdmultimedia.Orchestration', verbose_name="M.25.1 Parle-t-on du son et de l'orchestration, si oui pr\xe9cisez."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='premier_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas"), ("Disponible et consultable sur la page d'acc\xe8s", "L'outil est disponible et consultable sur la page d'acc\xe8s"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.17 Quel est le PREMIER onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sollicitation_generale',
            field=models.ManyToManyField(to='bdmultimedia.SollicitationGenerale', verbose_name='U.29 Pour comprendre le discours g\xe9n\xe9ral'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sollicitation_musicale',
            field=models.ManyToManyField(to='bdmultimedia.SollicitationMusicale', verbose_name='U.28 Pour comprendre le discours sur la musique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='troisieme_onglet',
            field=models.CharField(choices=[('Ne s\u2019applique pas', 'Ne s\u2019applique pas car le dispositif \xe9tait disponible sur la page d\u2019accueil'), ("Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page", "Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page"), ("On peut consulter l'outil directement sur cette troisi\xe8me page", "On peut consulter l'outil directement sur cette trois\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.19 Quel est le TROISIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
    ]
