# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0130_auto_20180601_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Organologie',
            },
        ),
        migrations.AddField(
            model_name='outil',
            name='organologie',
            field=models.ManyToManyField(to='bdmultimedia.Organologie', verbose_name='M.27.4 Parle-t-on d\u2019organologie?'),
        ),
    ]
