# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0131_auto_20180606_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outil',
            old_name='interface',
            new_name='interactivite',
        ),
    ]
