# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0133_auto_20180614_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='contexte',
            field=models.ManyToManyField(db_index=True, help_text='Si il est juste fait mention d\u2019une date sans donner plus d\u2019information sur ce qui se passait \xe0 l\u2019\xe9poque cocher \u201cNon\u201d.', to='bdmultimedia.Contexte', verbose_name="M.27.2 Parle-t-on du contexte de composition, cr\xe9ation, interpr\xe9tation de l'oeuvre, de l'instrument..."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='deux_onglet_autre',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='deuxieme_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas car l'outil \xe9tait disponible sur la page d'accueil"), ("On peut consulter l'outil directement sur cette deuxi\xe8me page", "On peut consulter l'outil directement sur cette deuxi\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], db_index=True, default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.18 Quel est le DEUXIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='ensemble_thematique_nom',
            field=models.CharField(blank=True, db_index=True, help_text='Ex: Camille raconte', max_length=200, verbose_name='R.3.2 Si oui, donnez le titre sous lequel est regroup\xe9 cet ensemble.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='epoque',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Avant le XII\xe8', 'Avant le XII\xe8'), ('XII\xe8', 'XII\xe8'), ('XIII\xe8', 'XIII\xe8'), ('XIV\xe8', 'XIV\xe8'), ('XV\xe8', 'XV\xe8'), ('XVI\xe8', 'XVI\xe8'), ('XVII\xe8', 'XVII\xe8'), ('XVIII\xe8', 'XVIII\xe8'), ('XIX\xe8', 'XIX\xe8'), ('XX\xe8', 'XX\xe8'), ('XXI\xe8', 'XXI\xe8'), ('nsp', 'nsp')], db_index=True, max_length=100, null=True, verbose_name='M.27.1 \xc9poque'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_autre',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.EvocationAutre', verbose_name='I.37 Interdisciplinarit\xe9'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_graphique',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.EvocationGraphique', verbose_name='EM.34 \xc9vocation graphique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_litteraire',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Texte oral', 'Texte oral'), ('Texte \xe9crit', 'Texte \xe9crit')], db_index=True, max_length=200, verbose_name='EM.36 \xc9vocation litt\xe9raire'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_plastique',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.EvocationPlastique', verbose_name='EM.35 \xc9vocation plastique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='exemples_notions_interdisciplinaires',
            field=models.ManyToManyField(blank=True, db_index=True, to='bdmultimedia.NotionsInter', verbose_name='I.39 Donner des exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='experience_musicale',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.ExperienceMusicale', verbose_name="M.26 Parle-t-on de l'experience musicale, si oui pr\xe9cisez."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='format',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.FormatOutil', verbose_name='R.7 Format du dispositif'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='forme_narrative',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.FormeNarrative', verbose_name='R.8 Formes narratives'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='genre_musical',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.GenreMusical', verbose_name='M.25.4 Parle-t-on du genre musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='interactivite',
            field=models.CharField(choices=[('Simple consultation', 'Simple consultation'), ('Participation limit\xe9e', "Participation limit\xe9e (l'usager est actif mais se contente de r\xe9pondre aux consignes)"), ('Participation dynamique', "Participation dynamique (l'usager co-construit le service)")], db_index=True, max_length=200, null=True, verbose_name='R.13 Interactivit\xe9'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='language_musical',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.LanguageMusical', verbose_name='M.25.3 Parle-t-on du language musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mode_consultation',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.ModeConsultation', verbose_name='S.21 Mode de consultation offert au public'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mode_hebergement',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.ModeHebergement', verbose_name="S.20 Mode d'h\xe9bergement sur la toile"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='narration_langue',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.LangueNarration', verbose_name='S.22 Langue du dispositif'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='orchestration',
            field=models.ManyToManyField(db_index=True, help_text='Registres (au sens de groupe de hauteur si cela concerne les registres de l\u2019orgue cocher \xab timbres \xbb)', to='bdmultimedia.Orchestration', verbose_name="M.25.1 Parle-t-on du son et de l'orchestration, si oui pr\xe9cisez."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='organologie',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.Organologie', verbose_name='M.27.4 Parle-t-on d\u2019organologie?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='personnification_service',
            field=models.CharField(choices=[('Service g\xe9n\xe9rique', 'Service g\xe9n\xe9rique'), ('Service sp\xe9cialis\xe9', 'Service sp\xe9cialis\xe9 (public cat\xe9goris\xe9)'), ('Service personnalis\xe9 et/ou individualis\xe9', 'Service personnalis\xe9 et/ou individualis\xe9')], db_index=True, max_length=200, null=True, verbose_name='R.14 Degr\xe9s de personnification du service'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='prem_onglet_autre',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='premier_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas"), ("Disponible et consultable sur la page d'acc\xe8s", "L'outil est disponible et consultable sur la page d'acc\xe8s"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], db_index=True, default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.17 Quel est le PREMIER onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_nom',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.ProducteurNom', verbose_name='R.5 Pr\xe9ciser le nom complet du/des producteur(s)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='producteur_type',
            field=models.ManyToManyField(db_index=True, help_text='Attention : r\xe9pondre \xe0 cette question n\xe9cessite d\u2019aller v\xe9rifier les statuts des organismes impliqu\xe9s ou le titre auquel ils s\u2019impliquent. Exemple . L\u2019OSM peut agir en tant que producteur pour un concert ou au titre de diffuseur pour un autre \xe9v\xe8nement.', to='bdmultimedia.ProdType', verbose_name='R.4 Qui est le producteur de ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_femme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleAnimauxFemmes', verbose_name='St\xe9.41.3 R\xf4le des animaux femelles'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_homme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleAnimauxHomme', verbose_name='St\xe9.41.2 R\xf4le des animaux m\xe2les'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_neutre',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleAnimauxNeutre', verbose_name='St\xe9.41.4 R\xf4le des animaux ind\xe9termin\xe9s'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_evolution',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleEvolution', verbose_name="M.27.3 Parle-t-on du r\xf4le et de l'\xe9volution du [m\xe9tier li\xe9s \xe0 la musique pr\xe9cisez]"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_femme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleFemmes', verbose_name='St\xe9.39.2 R\xf4le des femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_homme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleHomme', verbose_name='St\xe9.39.3 R\xf4le des hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_neutre',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleHumainNeutre', verbose_name='St\xe9.39.4 R\xf4le des indetermin\xe9s'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_femme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleInstrFemmes', verbose_name='St\xe9.42.3 R\xf4le des instruments anthropomorphes f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_homme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleInstrHomme', verbose_name='St\xe9.42.2 R\xf4le des instruments anthropomorphes masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_neutre',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RoleInstrNeutre', verbose_name='St\xe9.42.4 R\xf4le des instruments anthropomorphes neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_femme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RolePersAnimFemmes', verbose_name='St\xe9.40.3 R\xf4le des personnages anim\xe9s f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_homme',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RolePersAnimHomme', verbose_name='St\xe9.40.2 R\xf4le des personnages anim\xe9s masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_neutre',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.RolePersAnimNeutre', verbose_name='St\xe9.40.4 R\xf4le des personnages anim\xe9s ind\xe9termin\xe9s'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.CharField(db_index=True, help_text='Attention, enlever la barre oblique \xab / \xbb \xe0 la fin de l\u2019URL www.osm.ca. <br> Si le dispositif est une vid\xe9o d\u2019un-e YouTubeur-e, indiquer le lien vers sa cha\xeene YouTube.', max_length=200, verbose_name="R.3 URL d'acc\xe8s au site d'h\xe9bergement"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sollicitation_generale',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.SollicitationGenerale', verbose_name='U.29 Pour comprendre le discours g\xe9n\xe9ral'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sollicitation_musicale',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.SollicitationMusicale', verbose_name='U.28 Pour comprendre le discours sur la musique'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sonore_valeur',
            field=models.CharField(choices=[('Nsp', "Ne s'applique pas"), ('Premier plan', 'Premier Plan'), ('Arri\xe8re plan', 'Arri\xe8re plan'), ('Alternance', 'Alternance')], db_index=True, default='Nsp', max_length=200, verbose_name='PM.33 Mise en valeur du sonore'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sous_titre',
            field=models.ManyToManyField(db_index=True, help_text='Les sous-titrages automatiques propos\xe9s par YouTube n\u2019entrent pas en consid\xe9ration.', to='bdmultimedia.SousTitre', verbose_name='S.23 Sous-titrage'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='structure',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.Structure', verbose_name='M.25.2 Parle-t-on de la structure, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='style_musical',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.StyleMusical', verbose_name='M.25.5 Parle-t-on du style musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='support_diffusion',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.SupportDiffusion', verbose_name='R.6 Support de diffusion'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='trois_onglet_autre',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='troisieme_onglet',
            field=models.CharField(choices=[('Ne s\u2019applique pas', 'Ne s\u2019applique pas car le dispositif \xe9tait disponible sur la page d\u2019accueil'), ("Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page", "Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page"), ("On peut consulter l'outil directement sur cette troisi\xe8me page", "On peut consulter l'outil directement sur cette trois\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], db_index=True, default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.19 Quel est le TROISIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='url',
            field=models.CharField(db_index=True, help_text='Attention, enlever la barre oblique \xab / \xbb \xe0 la fin de l\u2019URL Ex. www.osm.ca/fr/matinees/#1488205065259-011decba-7105', max_length=200, unique=True, verbose_name="R.2 URL d'acc\xe8s direct"),
        ),
    ]
