# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0134_auto_20180614_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodtype',
            options={'verbose_name': 'type de producteur', 'verbose_name_plural': 'types de producteur'},
        ),
        migrations.AlterModelOptions(
            name='producteurnom',
            options={'verbose_name': 'Nom du producteur', 'verbose_name_plural': 'Noms des producteurs'},
        ),
    ]
