# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0135_auto_20180614_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contexte',
            options={'verbose_name': 'Contexte de composition, cr\xe9ation, interpr\xe9tation...', 'verbose_name_plural': 'Contextes de composition, cr\xe9ation, interpr\xe9tation...'},
        ),
        migrations.AlterModelOptions(
            name='evocationautre',
            options={'verbose_name': "\xc9vocation d'autre discipline", 'verbose_name_plural': "\xc9vocations d'autres disciplines"},
        ),
        migrations.AlterModelOptions(
            name='evocationgraphique',
            options={'verbose_name': '\xc9vocation graphique', 'verbose_name_plural': '\xc9vocations graphiques'},
        ),
        migrations.AlterModelOptions(
            name='evocationplastique',
            options={'verbose_name': '\xc9vocation plastique', 'verbose_name_plural': '\xc9vocations plastiques'},
        ),
        migrations.AlterModelOptions(
            name='experiencemusicale',
            options={'verbose_name': 'Experience musicale', 'verbose_name_plural': 'Experiences musicales'},
        ),
        migrations.AlterModelOptions(
            name='formenarrative',
            options={'verbose_name': 'Forme narrative', 'verbose_name_plural': 'Formes narratives'},
        ),
        migrations.AlterModelOptions(
            name='genremusical',
            options={'verbose_name': 'Genre musical', 'verbose_name_plural': 'Genres musicaux'},
        ),
        migrations.AlterModelOptions(
            name='languagemusical',
            options={'verbose_name': 'Language musical', 'verbose_name_plural': 'Languages musicaux'},
        ),
        migrations.AlterModelOptions(
            name='languenarration',
            options={'verbose_name': 'Langue de la narration', 'verbose_name_plural': 'Langues de narration'},
        ),
        migrations.AlterModelOptions(
            name='modeconsultation',
            options={'verbose_name': 'Mode de consultation offert au public', 'verbose_name_plural': 'Modes de consultation offerts au public'},
        ),
        migrations.AlterModelOptions(
            name='modehebergement',
            options={'verbose_name': "Mode d'h\xe9bergement sur la toile", 'verbose_name_plural': "Modes d'h\xe9bergement sur la toile"},
        ),
        migrations.AlterModelOptions(
            name='notionsinter',
            options={'verbose_name': 'Exemple de notion \xe9voqu\xe9e de fa\xe7on interdisciplinaire', 'verbose_name_plural': 'Exemples de notions \xe9voqu\xe9es de fa\xe7on interdisciplinaires'},
        ),
        migrations.AlterModelOptions(
            name='orchestration',
            options={'verbose_name': 'Son et orchestration', 'verbose_name_plural': 'Sons et orchestrations'},
        ),
        migrations.AlterModelOptions(
            name='roleevolution',
            options={'verbose_name': 'R\xf4le et \xe9volution du m\xe9tier', 'verbose_name_plural': 'R\xf4les et \xe9volutions des m\xe9tiers'},
        ),
        migrations.AlterModelOptions(
            name='rolehumainneutre',
            options={'verbose_name': 'Role des humains ind\xe9termin\xe9'},
        ),
        migrations.AlterModelOptions(
            name='sollicitationgenerale',
            options={'verbose_name': 'Sollicitation g\xe9n\xe9rale', 'verbose_name_plural': 'Sollicitations g\xe9n\xe9rales'},
        ),
        migrations.AlterModelOptions(
            name='sollicitationmusicale',
            options={'verbose_name': 'Sollicitation musicale', 'verbose_name_plural': 'Sollicitations musicales'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Structure'},
        ),
        migrations.AlterModelOptions(
            name='stylemusical',
            options={'verbose_name': 'Style musical', 'verbose_name_plural': 'Styles musicaux'},
        ),
        migrations.AlterModelOptions(
            name='supportdiffusion',
            options={'verbose_name': 'support de diffusion', 'verbose_name_plural': 'supports de diffusion'},
        ),
    ]
