# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0136_auto_20180614_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formatoutil',
            options={'verbose_name': 'format du dispositif', 'verbose_name_plural': 'Formats de dispositif'},
        ),
    ]
