# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 22:55
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0137_auto_20180614_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='evocation_litteraire',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Texte oral', 'Texte oral'), ('Texte \xe9crit', 'Texte \xe9crit')], db_index=True, help_text='Le mat\xe9riau musical est-il d\xe9crit \u201cen mots\u201d dans le dispositif ?', max_length=200, verbose_name='EM.36 \xc9vocation litt\xe9raire'),
        ),
    ]
