# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-08 15:48
from __future__ import unicode_literals

import bdmultimedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0138_auto_20180620_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', bdmultimedia.models.CustomDateField()),
            ],
        ),
    ]
