# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0138_auto_20180620_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='deux_onglet_autre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='deuxieme_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas car l'outil \xe9tait disponible sur la page d'accueil"), ("On peut consulter l'outil directement sur cette deuxi\xe8me page", "On peut consulter l'outil directement sur cette deuxi\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.18 Quel est le DEUXIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_litteraire',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Non', 'Non'), ('Texte oral', 'Texte oral'), ('Texte \xe9crit', 'Texte \xe9crit')], help_text='Le mat\xe9riau musical est-il d\xe9crit \u201cen mots\u201d dans le dispositif ?', max_length=200, verbose_name='EM.36 \xc9vocation litt\xe9raire'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='genre_musical',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.GenreMusical', verbose_name='M.25.4 Parle-t-on du genre musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='language_musical',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.LanguageMusical', verbose_name='M.25.3 Parle-t-on du language musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mise_en_ligne_date',
            field=models.DateField(blank=True, help_text="Si seule l\u2019ann\xe9e de mise en ligne est disponible entrer la date de mise en ligne au 1er janvier de l\u2019ann\xe9e concern\xe9e. Si la date n'est pas disponible, laisser vide.", null=True, verbose_name='R.11 Date de la mise en ligne'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mode_consultation',
            field=models.ManyToManyField(to='bdmultimedia.ModeConsultation', verbose_name='S.21 Mode de consultation offert au public'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_animaux_total',
            field=models.CharField(default='0', help_text='Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, null=True, verbose_name="St\xe9.41.1 Nombre d'animaux total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_humains_total',
            field=models.CharField(default='0', help_text='On compte tous les humains qui sont 3 ou moins dans le cadre. Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, verbose_name="St\xe9.39.1 Nombre d'humains total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_total',
            field=models.CharField(default='0', help_text='cf. anthropomorphe. Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pages',
            field=models.CharField(help_text="Correspond au nombre de page web sur lesquelles se d\xe9cline le  dispositif. Nsp = ne s'applique pas. Si plus que 20 pages, inscrire : plus de 20 pages", max_length=16, null=True, verbose_name='R.10 Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_total',
            field=models.CharField(default='0', help_text='Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, null=True, verbose_name='St\xe9.40.1 Nombre de personnages anim\xe9s total'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_concepts',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Nsp', "Ne s'applique pas")], default='Nsp', max_length=20, verbose_name='I.38 \xc0 partir de quelle notion? - Notions communes (luminosit\xe9, transparence, vitesse, mouvement)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_experiences',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Nsp', "Ne s'applique pas")], default='Nsp', max_length=20, verbose_name='I.38 \xc0 partir de quelle notion? - Exp\xe9rience (\xe9motions)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='notion_pratiques',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Nsp', "Ne s'applique pas")], default='Nsp', max_length=20, verbose_name='I.38 \xc0 partir de quelle notion? - Pratique (processus de cr\xe9ation)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='orchestration',
            field=models.ManyToManyField(db_index=True, default=1, help_text='Registres (au sens de groupe de hauteur si cela concerne les registres de l\u2019orgue cocher \xab timbres \xbb)', to='bdmultimedia.Orchestration', verbose_name="M.25.1 Parle-t-on du son et de l'orchestration, si oui pr\xe9cisez."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='personnification_service',
            field=models.CharField(choices=[('Service g\xe9n\xe9rique', 'Service g\xe9n\xe9rique'), ('Service sp\xe9cialis\xe9', 'Service sp\xe9cialis\xe9 (public cat\xe9goris\xe9)'), ('Service personnalis\xe9 et/ou individualis\xe9', 'Service personnalis\xe9 et/ou individualis\xe9')], max_length=200, null=True, verbose_name='R.14 Degr\xe9s de personnification du service'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='prem_onglet_autre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='premier_onglet',
            field=models.CharField(choices=[("Ne s'applique pas", "Ne s'applique pas"), ("Disponible et consultable sur la page d'acc\xe8s", "L'outil est disponible et consultable sur la page d'acc\xe8s"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.17 Quel est le PREMIER onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_femme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleAnimauxFemmes', verbose_name='St\xe9.41.3 R\xf4le des animaux femelles'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_homme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleAnimauxHomme', verbose_name='St\xe9.41.2 R\xf4le des animaux m\xe2les'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_animaux_neutre',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleAnimauxNeutre', verbose_name='St\xe9.41.4 R\xf4le des animaux ind\xe9termin\xe9s'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_femme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleFemmes', verbose_name='St\xe9.39.2 R\xf4le des femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_homme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleHomme', verbose_name='St\xe9.39.3 R\xf4le des hommes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_humain_neutre',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleHumainNeutre', verbose_name='St\xe9.39.4 R\xf4le des ind\xe9termin\xe9s'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_femme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleInstrFemmes', verbose_name='St\xe9.42.3 R\xf4le des instruments anthropomorphes f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_homme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleInstrHomme', verbose_name='St\xe9.42.2 R\xf4le des instruments anthropomorphes masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_instr_anime_neutre',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleInstrNeutre', verbose_name='St\xe9.42.4 R\xf4le des instruments anthropomorphes neutres'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_femme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RolePersAnimFemmes', verbose_name='St\xe9.40.3 R\xf4le des personnages anim\xe9s f\xe9minins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_homme',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RolePersAnimHomme', verbose_name='St\xe9.40.2 R\xf4le des personnages anim\xe9s masculins'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_pers_anime_neutre',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RolePersAnimNeutre', verbose_name='St\xe9.40.4 R\xf4le des personnages anim\xe9s ind\xe9termin\xe9s'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.CharField(db_index=True, help_text='Attention, enlever la barre oblique \xab / \xbb \xe0 la fin de l\u2019URL www.osm.ca. Si le dispositif est une vid\xe9o d\u2019un-e YouTubeur-e, indiquer le lien vers sa cha\xeene YouTube.', max_length=200, verbose_name="R.3 URL d'acc\xe8s au site d'h\xe9bergement"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sonore_valeur',
            field=models.CharField(choices=[('Nsp', "Ne s'applique pas"), ('Premier plan', 'Premier Plan'), ('Arri\xe8re plan', 'Arri\xe8re plan'), ('Alternance', 'Alternance')], default='Nsp', max_length=200, verbose_name='PM.33 Mise en valeur du sonore'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='structure',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.Structure', verbose_name='M.25.2 Parle-t-on de la structure, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='style_musical',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.StyleMusical', verbose_name='M.25.5 Parle-t-on du style musical, si oui pr\xe9cisez.'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='titre',
            field=models.CharField(db_index=True, help_text='Tout support disponible en ligne ne perdant rien \xe0 \xeatre imprim\xe9 n\u2019entre pas dans le corpus analys\xe9 ici.', max_length=200, verbose_name='R.1 Titre du dispositif'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='trois_onglet_autre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Si autre, pr\xe9cisez'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='troisieme_onglet',
            field=models.CharField(choices=[('Ne s\u2019applique pas', 'Ne s\u2019applique pas car le dispositif \xe9tait disponible sur la page d\u2019accueil'), ("Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page", "Ne s'applique pas car l'outil \xe9tait disponible sur la deuxi\xe8me page"), ("On peut consulter l'outil directement sur cette troisi\xe8me page", "On peut consulter l'outil directement sur cette trois\xe8me page"), ('Action culturelle', 'Action culturelle'), ('M\xe9diation', 'M\xe9diation'), ('\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que', '\xc9ducation, Apprendre, Le\xe7on, Educoth\xe8que'), ('Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental', 'Exp\xe9rimentation, d\xe9couvrir, exp\xe9rimental'), ('Pour tous les publics', 'Pour tout les publics'), ("L'orchestre et vous", "L'orchestre et vous"), ("Guide d'\xe9coute", "Guide d'\xe9coute"), ('Livret p\xe9dagogique', 'Livret p\xe9dagogique'), ('Pour les enseignants, \xe9coles, scolaires', 'Pour les enseignants, \xe9coles, scolaires'), ('Le nom du dispositif lui m\xeame', "Le nom du dispositif lui m\xeame (ex: 'La galerie symphonique')"), ('Ressources en ligne, ressources num\xe9riques, ressources', 'Ressources en ligne, ressources num\xe9riques, ressources'), ('Relatif \xe0 la programmation', 'Est relatif \xe0 la programmation \xe0 laquelle il fait r\xe9f\xe9rence (onglet du concert, titre du compositeur, etc.)'), ("Relatif au format du dispositif dont il s'agit", "Est relatif au format du dispositif dont il s'agit (Balado, vid\xe9o, playlist, web s\xe9rie, etc.)"), ("Relatif au site d'h\xe9bergement", "Est relatif au site d'h\xe9bergement"), ('\xc0 propos', '\xc0 propos'), ('Voir et entendre', 'Voir et entendre'), ('Actualit\xe9s, news, nouveaut\xe9', 'Actualit\xe9, news, nouveaut\xe9'), ('Pour tous les publics', 'Pour tous les publics'), ('Pour un public sp\xe9cifique', 'Pour un public sp\xe9cifique'), ('Musique', 'Musique'), ('Autre', 'Autre')], default="Ne s'applique pas", max_length=200, null=True, verbose_name='S.19 Quel est le TROISIEME onglet \xe0 ouvrir pour trouver ce dispositif?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='utilisateur',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
