# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-08 15:50
from __future__ import unicode_literals

import bdmultimedia.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0139_customtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtest',
            name='date',
            field=bdmultimedia.models.CustomDateField(verbose_name='TEST DATE'),
        ),
    ]
