# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0139_auto_20181024_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='contexte',
            field=models.ManyToManyField(db_index=True, default=1, help_text='Si il est juste fait mention d\u2019une date sans donner plus d\u2019information sur ce qui se passait \xe0 l\u2019\xe9poque cocher \u201cNon\u201d.', to='bdmultimedia.Contexte', verbose_name="M.27.2 Parle-t-on du contexte de composition, cr\xe9ation, interpr\xe9tation de l'oeuvre, de l'instrument..."),
        ),
        migrations.AlterField(
            model_name='outil',
            name='epoque',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Avant le XII\xe8', 'Avant le XII\xe8'), ('XII\xe8', 'XII\xe8'), ('XIII\xe8', 'XIII\xe8'), ('XIV\xe8', 'XIV\xe8'), ('XV\xe8', 'XV\xe8'), ('XVI\xe8', 'XVI\xe8'), ('XVII\xe8', 'XVII\xe8'), ('XVIII\xe8', 'XVIII\xe8'), ('XIX\xe8', 'XIX\xe8'), ('XX\xe8', 'XX\xe8'), ('XXI\xe8', 'XXI\xe8'), ('nsp', 'nsp')], db_index=True, default='nsp', max_length=100, null=True, verbose_name='M.27.1 \xc9poque'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='organologie',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.Organologie', verbose_name='M.27.4 Parle-t-on d\u2019organologie?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='role_evolution',
            field=models.ManyToManyField(db_index=True, default=1, to='bdmultimedia.RoleEvolution', verbose_name="M.27.3 Parle-t-on du r\xf4le et de l'\xe9volution du [m\xe9tier li\xe9s \xe0 la musique pr\xe9cisez]"),
        ),
    ]
