# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-08 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0140_auto_20180708_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTest',
        ),
    ]
