# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0141_auto_20181108_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='query',
            name='nom',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AddField(
            model_name='outil',
            name='epoque_bis',
            field=models.ManyToManyField(db_index=True, default=12, to='bdmultimedia.Epoque', verbose_name='M.27.1 \xc9poque'),
        ),
    ]
