# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-09 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0141_delete_customtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='nb_animaux_total',
            field=models.CharField(default='0', help_text='Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, null=True, verbose_name="St\xe9.41.1 Nombre d'animaux total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_humains_total',
            field=models.CharField(default='0', help_text='On compte tous les humains qui sont 3 ou moins dans le cadre. Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, verbose_name="St\xe9.39.1 Nombre d'humains total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_instr_anime_total',
            field=models.CharField(default='0', help_text='cf. anthropomorphe. Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, null=True, verbose_name="St\xe9.42.1 Nombre d'instruments anim\xe9s total"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pages',
            field=models.CharField(help_text="Correspond au nombre de page web sur lesquelles se d\xe9cline le  dispositif. Nsp = ne s'applique pas. Si plus que 20 pages, inscrire : plus de 20 pages", max_length=16, null=True, verbose_name='R.10 Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='nb_pers_anime_total',
            field=models.CharField(default='0', help_text='Si le nombre exc\xe8de 11, \xe9crire "11 et plus"', max_length=10, null=True, verbose_name='St\xe9.40.1 Nombre de personnages anim\xe9s total'),
        ),
    ]
