# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0142_auto_20180709_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='notion_experiences',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('Nsp', "Ne s'applique pas")], default='Nsp', max_length=3, verbose_name='I.38 \xc0 partir de quelle notion? - Exp\xe9rience (\xe9motions)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='site',
            field=models.CharField(db_index=True, help_text='Attention, enlever la barre oblique \xab / \xbb \xe0 la fin de l\u2019URL www.osm.ca. Si le dispositif est une vid\xe9o d\u2019un-e YouTubeur-e, indiquer le lien vers sa cha\xeene YouTube.', max_length=200, verbose_name="R.3 URL d'acc\xe8s au site d'h\xe9bergement"),
        ),
    ]
