# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0142_auto_20181109_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outil',
            name='epoque',
        ),
    ]
