# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0143_remove_outil_epoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outil',
            old_name='epoque_bis',
            new_name='epoque',
        ),
    ]
