# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-05 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0145_auto_20180905_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTest',
        ),
    ]
