# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0145_auto_20181109_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='outil',
            name='lien',
            field=models.URLField(null=True, verbose_name='Lien internet vers cet outil'),
        ),
        migrations.AddField(
            model_name='outil',
            name='organisme',
            field=models.CharField(max_length=400, null=True, verbose_name="Quel est le nom de l'organisme que vous repre\u0301sentez ?"),
        ),
        migrations.AddField(
            model_name='outil',
            name='outil_nom',
            field=models.CharField(max_length=400, null=True, verbose_name="Quel le nom de l'outil a\u0300 propos duquel vous allez remplir ce questionnaire ?"),
        ),
        migrations.AddField(
            model_name='outil',
            name='programmation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[("Je n'ai pas de programmation", "Je n'ai pas de programmation"), ('Oui, en lien avec la programmation de concert', 'Oui, en lien avec la programmation de concert'), ('Oui, en lien avec la programmation pe\u0301dagogique', 'Oui, en lien avec la programmation pe\u0301dagogique'), ('Non', 'Non')], default='Non', max_length=126, verbose_name='Cet outil a-t-il e\u0301te\u0301 conc\u0327u en lien avec votre programmation ?'),
        ),
    ]
