# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0147_outil_duree_conception'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='duree_disponibilite',
            field=models.CharField(choices=[('Un mois ou moins', 'Un mois ou moins'), ('Entre deux et six mois', 'Entre deux et six mois'), ('Entre six mois et un an', 'Entre six mois et un an'), ('Entre deux et cinq ans', 'Entre deux et cinq ans'), ('Plus de cinq ans', 'Plus de cinq ans'), ('De fac\u0327on permanente', 'De fac\u0327on permanente')], max_length=50, null=True, verbose_name='Sa disponibilite\u0301 en ligne est pre\u0301vue pour durer'),
        ),
        migrations.AddField(
            model_name='outil',
            name='duree_realisation',
            field=models.CharField(choices=[('Un mois ou moins', 'Un mois ou moins'), ('Entre deux et six mois', 'Entre deux et six mois'), ('Entre six mois et un an', 'Entre six mois et un an'), ('Entre deux et cinq ans', 'Entre deux et cinq ans'), ('Plus de cinq ans', 'Plus de cinq ans'), ('De fac\u0327on permanente', 'De fac\u0327on permanente')], max_length=50, null=True, verbose_name='La dure\u0301e du travail ne\u0301cessaire a\u0300 sa re\u0301alisation/production a e\u0301te\u0301 de'),
        ),
        migrations.AddField(
            model_name='outil',
            name='iniciateur',
            field=models.CharField(max_length=400, null=True, verbose_name="Quelles e\u0301taient les personnes a\u0300 l'initiative de ce projet ? Donner leur fonction et leur statut (ex. le/la responsable du de\u0301veloppement des publics)"),
        ),
        migrations.AddField(
            model_name='outil',
            name='mediateur_professionnel',
            field=models.CharField(choices=[('Oui, a\u0300 temps plein', 'Oui, a\u0300 temps plein'), ('Oui, a\u0300 temps partiel', 'Oui, a\u0300 temps partiel'), ('Non', 'Non'), ('Ne sais pas', 'Ne sais pas')], max_length=50, null=True, verbose_name=" Avez-vous fait appel a\u0300 un me\u0301diateur professionnel ou a\u0300 quelqu'un dont les ta\u0302ches sont associe\u0301es aux activite\u0301s de me\u0301diation (de votre organisme ou inde\u0301pendant) pour concevoir ce dispositif ?"),
        ),
        migrations.AddField(
            model_name='outil',
            name='responsable',
            field=models.CharField(max_length=400, null=True, verbose_name=' Quels e\u0301taient les responsables de ce projet ? Donner leur fonction et leur statut ( ex. un.e stagiaire du de\u0301partement marketing)'),
        ),
    ]
