# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-21 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0147_auto_20180919_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='role_humain_femme',
            field=models.ManyToManyField(db_index=True, default=0, to='bdmultimedia.RoleFemmes', verbose_name='St\xe9.39.2 R\xf4le des femmes'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='titre',
            field=models.CharField(db_index=True, help_text='Tout support disponible en ligne ne perdant rien \xe0 \xeatre imprim\xe9 n\u2019entre pas dans le corpus analys\xe9 ici.', max_length=200, verbose_name='R.1 Titre du dispositif'),
        ),
    ]
