# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0148_auto_20180921_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='role_humain_femme',
            field=models.ManyToManyField(db_index=True, default='Pas de femmes', to='bdmultimedia.RoleFemmes', verbose_name='St\xe9.39.2 R\xf4le des femmes'),
        ),
    ]
