# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0148_auto_20181218_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='forme_delegation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sous-traitance', 'Sous-traitance'), ('Collaboration (avec une e\u0301cole professionnelle, avec une start up, etc.)', 'Collaboration (avec une e\u0301cole professionnelle, avec une start up, etc.)'), ('Partenariat (publicitaire, de recherche, etc.)', 'Partenariat (publicitaire, de recherche, etc.)'), ("Mecenat (re\u0301alise\u0301 gra\u0302ce be\u0301ne\u0301volat d'employe\u0301s d'une entreprise prive\u0301e)", "Mecenat (re\u0301alise\u0301 gra\u0302ce be\u0301ne\u0301volat d'employe\u0301s d'une entreprise prive\u0301e)"), ('Autre', 'Autre')], max_length=400, null=True, verbose_name='Quelle forme a pris la de\u0301le\u0301gation de la re\u0301alisation/production de cet outil ?'),
        ),
        migrations.AddField(
            model_name='outil',
            name='forme_delegation_autre',
            field=models.CharField(max_length=400, null=True, verbose_name='Autre, pr\xe9cisez.'),
        ),
        migrations.AddField(
            model_name='outil',
            name='sous_traitant',
            field=models.CharField(choices=[('Oui, entie\u0300rement', 'Oui, entie\u0300rement'), ('Oui, en partie', 'Oui, en partie'), ('Non', 'Non')], max_length=20, null=True, verbose_name='Avez-vous confie\u0301 la re\u0301alisation/production de cet outil a\u0300 des personnes exte\u0301rieures a\u0300 votre organisme ?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mediateur_professionnel',
            field=models.CharField(choices=[('Oui, a\u0300 temps plein', 'Oui, a\u0300 temps plein'), ('Oui, a\u0300 temps partiel', 'Oui, a\u0300 temps partiel'), ('Non', 'Non'), ('Ne sais pas', 'Ne sais pas')], max_length=50, null=True, verbose_name="Avez-vous fait appel a\u0300 un me\u0301diateur professionnel ou a\u0300 quelqu'un dont les ta\u0302ches sont associe\u0301es aux activite\u0301s de me\u0301diation (de votre organisme ou inde\u0301pendant) pour concevoir ce dispositif ?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='responsable',
            field=models.CharField(max_length=400, null=True, verbose_name='Quels e\u0301taient les responsables de ce projet ? Donner leur fonction et leur statut ( ex. un.e stagiaire du de\u0301partement marketing)'),
        ),
    ]
