# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0149_auto_20181218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='cout',
            field=models.PositiveIntegerField(default=0, verbose_name='Quel est le cou\u0302t approximatif de la re\u0301alisation/production de cet outil ? (en nombre ex: 2000$)'),
        ),
        migrations.AddField(
            model_name='outil',
            name='realisateur',
            field=models.CharField(max_length=400, null=True, verbose_name="Qui a re\u0301alise\u0301/produit ce ce projet ? (nom de l'entreprise si il y a lieu, sinon, fonction et statut du responsable de la mise en \u0153uvre du projet)"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='forme_delegation_autre',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Autre, pr\xe9cisez.'),
        ),
    ]
