# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0150_auto_20181218_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='action_utilisateurs',
            field=models.TextField(null=True, verbose_name='Comple\u0301tez cette phrase : en cre\u0301ant ce dispositif notre objectif e\u0301tait que ses utilisateurs...'),
        ),
        migrations.AddField(
            model_name='outil',
            name='usager',
            field=multiselectfield.db.fields.MultiSelectField(max_length=400, null=True, verbose_name=' Quel est le rapport entre les usagers que vous imaginiez pour ce dispositif et votre organisme ?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='realisateur',
            field=models.CharField(max_length=400, null=True, verbose_name="Qui a re\u0301alise\u0301/produit ce projet ? (nom de l'entreprise si il y a lieu, sinon, fonction et statut du responsable de la mise en \u0153uvre du projet)"),
        ),
    ]
