# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0152_auto_20181218_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='action_delegation_autre',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Autre, pr\xe9cisez.'),
        ),
    ]
