# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0153_outil_action_delegation_autre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='lien',
            field=models.URLField(blank=True, null=True, verbose_name='Lien internet vers cet outil'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='outil_nom',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Quel le nom de l'outil a\u0300 propos duquel vous allez remplir ce questionnaire ?"),
        ),
    ]
