# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0154_auto_20181218_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='action',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("D'e\u0301ducation musicale", "D'e\u0301ducation musicale"), ('De de\u0301veloppement de public', 'De de\u0301veloppement de public'), ('Publicitaire et promotionnelle', 'Publicitaire et promotionnelle'), ('De me\u0301diation de la musique', 'De me\u0301diation de la musique'), ('Autre', 'Autre')], max_length=200, null=True, verbose_name='Cet outil sert une action (plusieurs choix possibles)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='action_utilisateurs',
            field=models.TextField(blank=True, null=True, verbose_name='Comple\u0301tez cette phrase : en cre\u0301ant ce dispositif notre objectif e\u0301tait que ses utilisateurs...'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='cout',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Quel est le cou\u0302t approximatif de la re\u0301alisation/production de cet outil ? (en nombre ex: 2000$)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='duree_conception',
            field=models.CharField(blank=True, choices=[('Un mois ou moins', 'Un mois ou moins'), ('Entre deux et six mois', 'Entre deux et six mois'), ('Entre six mois et un an', 'Entre six mois et un an'), ('Entre deux et cinq ans', 'Entre deux et cinq ans'), ('Plus de cinq ans', 'Plus de cinq ans'), ('De fac\u0327on permanente', 'De fac\u0327on permanente')], max_length=50, null=True, verbose_name='La conception du contenu de ce outil a e\u0301te\u0301 de'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='duree_disponibilite',
            field=models.CharField(blank=True, choices=[('Un mois ou moins', 'Un mois ou moins'), ('Entre deux et six mois', 'Entre deux et six mois'), ('Entre six mois et un an', 'Entre six mois et un an'), ('Entre deux et cinq ans', 'Entre deux et cinq ans'), ('Plus de cinq ans', 'Plus de cinq ans'), ('De fac\u0327on permanente', 'De fac\u0327on permanente')], max_length=50, null=True, verbose_name='Sa disponibilite\u0301 en ligne est pre\u0301vue pour durer'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='duree_realisation',
            field=models.CharField(blank=True, choices=[('Un mois ou moins', 'Un mois ou moins'), ('Entre deux et six mois', 'Entre deux et six mois'), ('Entre six mois et un an', 'Entre six mois et un an'), ('Entre deux et cinq ans', 'Entre deux et cinq ans'), ('Plus de cinq ans', 'Plus de cinq ans'), ('De fac\u0327on permanente', 'De fac\u0327on permanente')], max_length=50, null=True, verbose_name='La dure\u0301e du travail ne\u0301cessaire a\u0300 sa re\u0301alisation/production a e\u0301te\u0301 de'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Addresse courriel'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='forme_delegation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sous-traitance', 'Sous-traitance'), ('Collaboration (avec une e\u0301cole professionnelle, avec une start up, etc.)', 'Collaboration (avec une e\u0301cole professionnelle, avec une start up, etc.)'), ('Partenariat (publicitaire, de recherche, etc.)', 'Partenariat (publicitaire, de recherche, etc.)'), ("Mecenat (re\u0301alise\u0301 gra\u0302ce be\u0301ne\u0301volat d'employe\u0301s d'une entreprise prive\u0301e)", "Mecenat (re\u0301alise\u0301 gra\u0302ce be\u0301ne\u0301volat d'employe\u0301s d'une entreprise prive\u0301e)"), ('Autre', 'Autre')], max_length=400, null=True, verbose_name='Quelle forme a pris la de\u0301le\u0301gation de la re\u0301alisation/production de cet outil ?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='iniciateur',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Quelles e\u0301taient les personnes a\u0300 l'initiative de ce projet ? Donner leur fonction et leur statut (ex. le/la responsable du de\u0301veloppement des publics)"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='mediateur_professionnel',
            field=models.CharField(blank=True, choices=[('Oui, a\u0300 temps plein', 'Oui, a\u0300 temps plein'), ('Oui, a\u0300 temps partiel', 'Oui, a\u0300 temps partiel'), ('Non', 'Non'), ('Ne sais pas', 'Ne sais pas')], max_length=50, null=True, verbose_name="Avez-vous fait appel a\u0300 un me\u0301diateur professionnel ou a\u0300 quelqu'un dont les ta\u0302ches sont associe\u0301es aux activite\u0301s de me\u0301diation (de votre organisme ou inde\u0301pendant) pour concevoir ce dispositif ?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='organisme',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Quel est le nom de l'organisme que vous repre\u0301sentez ?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='programmation',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("Je n'ai pas de programmation", "Je n'ai pas de programmation"), ('Oui, en lien avec la programmation de concert', 'Oui, en lien avec la programmation de concert'), ('Oui, en lien avec la programmation pe\u0301dagogique', 'Oui, en lien avec la programmation pe\u0301dagogique'), ('Non', 'Non')], default='Non', max_length=126, verbose_name='Cet outil a-t-il e\u0301te\u0301 conc\u0327u en lien avec votre programmation ?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='public_cible',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pas de public cible', 'Pas de public cible'), ('Nourisson et petite enfance (0 a\u0300 3 ans)', 'Nourisson et petite enfance (0 a\u0300 3 ans)'), ('Enfants (4 a\u0300 12 ans)', 'Enfants (4 a\u0300 12 ans)'), ('Adolescents (13 a\u0300 16 ans)', 'Adolescents (13 a\u0300 16 ans)'), ('Adulescents (16 a\u0300 18 ans)', 'Adulescents (16 a\u0300 18 ans)'), ('Jeunes actifs (19 a\u0300 25 ans)', 'Jeunes actifs (19 a\u0300 25 ans)'), ('Actifs (25 a\u0300 65 ans)', 'Actifs (25 a\u0300 65 ans)'), ('Retraite\u0301s -(plus de 65 ans)', 'Retraite\u0301s -(plus de 65 ans)')], max_length=300, null=True, verbose_name="Quelle est la tranche d'a\u0302ge du public cible de cet outil ?"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='realisateur',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Qui a re\u0301alise\u0301/produit ce projet ? (nom de l'entreprise si il y a lieu, sinon, fonction et statut du responsable de la mise en \u0153uvre du projet)"),
        ),
        migrations.AlterField(
            model_name='outil',
            name='responsable',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Quels e\u0301taient les responsables de ce projet ? Donner leur fonction et leur statut ( ex. un.e stagiaire du de\u0301partement marketing)'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='sous_traitant',
            field=models.CharField(blank=True, choices=[('Oui, entie\u0300rement', 'Oui, entie\u0300rement'), ('Oui, en partie', 'Oui, en partie'), ('Non', 'Non')], max_length=20, null=True, verbose_name='Avez-vous confie\u0301 la re\u0301alisation/production de cet outil a\u0300 des personnes exte\u0301rieures a\u0300 votre organisme ?'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='usager',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=400, null=True, verbose_name=' Quel est le rapport entre les usagers que vous imaginiez pour ce dispositif et votre organisme ?'),
        ),
    ]
