# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0155_auto_20181228_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='outil',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
