# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0156_outil_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
    ]
