# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 20:11
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields
import sortedm2m.operations


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0158_remove_outil_slug'),
    ]

    operations = [
        sortedm2m.operations.AlterSortedManyToManyField(
            model_name='outil',
            name='forme_narrative',
            field=sortedm2m.fields.SortedManyToManyField(db_index=True, help_text=None, to='bdmultimedia.FormeNarrative', verbose_name='R.8 Formes narratives'),
        ),
    ]
