# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdmultimedia', '0159_auto_20190111_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='temps',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='outil',
            name='epoque',
            field=models.ManyToManyField(db_index=True, help_text='Inscrire les \xe9poques \xe9voqu\xe9es dans le dispositif (non pas l\u2019\xe9poque de tournage du dispositif).<br> Cocher une \xe9poque seulement lorsqu\'elle est d\xe9velopp\xe9e. Si un ph\xe9nom\xe8ne musical est \xe9voqu\xe9 de fa\xe7on transversale et dispers\xe9e dans le temps, sans focus, cocher "hors temps", un dispositif peut se retrouver dans une case "temporelle" et "hors temps" cf. <a href = https://www.youtube.com/watch?v=fSKBwjWE7NQ target=\'_blank\'>https://www.youtube.com/watch?v=fSKBwjWE7NQ</a>', to='bdmultimedia.Epoque', verbose_name='M.27.1 \xc9poque'),
        ),
        migrations.AlterField(
            model_name='outil',
            name='evocation_autre',
            field=models.ManyToManyField(db_index=True, to='bdmultimedia.EvocationAutre', verbose_name='I.37 Autres disciplines \xe9voqu\xe9es?'),
        ),
    ]
